{"kind":"symbol","metadata":{"roleHeading":"Framework","title":"NeiryKit","modules":[{"name":"NeiryKit"}],"externalID":"NeiryKit","symbolKind":"module","role":"collection"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Неофициальный фрейворк для работы с устройствами компании Neiry. Фреймворк является оберткой над основным SDK компании, который называется CapsuleClient.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Фреймворк работает только с ios. SDK тестировался мало, гарантий стабильной работы нет."}]},{"anchor":"%D0%98%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-sdk","text":"Инициализация sdk","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Для работы с устройствами требуется подключить динамическую библиотеку NeiryKit.framework в проект. Внутри фреймворка находится файл официальной библиотеки CapsuleClient.framework, который также нужно подключить как динамическую бибилиотеку."}]},{"level":2,"text":"Разрешения","anchor":"%D0%A0%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Чтобы фреймворк мог взаимодействовать с устройствами по bluetooth, требуется прописать разрешения в plist файле."}]},{"type":"codeListing","syntax":null,"code":["<key>NSBluetoothAlwaysUsageDescription<\/key>","<string>Для работы с устройстввами Neiry<\/string>"]},{"type":"heading","level":2,"anchor":"%D0%9A%D0%BE%D0%B4-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8","text":"Код интеграции"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Для начала создаем объект SDK"}]},{"syntax":null,"type":"codeListing","code":["let neiry = Neiry()"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Указываем делегат"}]},{"type":"codeListing","syntax":null,"code":["neiry.delegate = self"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Вызываем функцию "},{"type":"reference","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/create(address:name:type:)","isActive":true},{"text":" для создание объекта CapsuleClient","type":"text"}]},{"type":"codeListing","code":["neiry.create(address: .inprocess, name: \"Test sdk\", type: TYPE_HEADBAND)"],"syntax":null},{"inlineContent":[{"text":"Для запуска поиска bluetooth устройств нужно вызвать метод ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/requestDevices()","isActive":true}],"type":"paragraph"},{"syntax":null,"code":["neiry.requestDevices()"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"И ловить в делегате в методе "},{"isActive":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onDevices(devices:)","type":"reference"},{"text":" список найденых устройств.","type":"text"}]},{"type":"codeListing","syntax":null,"code":["func onDevices(devices: [NeiryDevice]) {","    ","}"]},{"type":"paragraph","inlineContent":[{"text":"Этот список можно отобразить на экране и дать пользователю выбрать и подключить устройство.","type":"text"}]},{"type":"codeListing","syntax":null,"code":["neiry.connect(to: device)"]},{"inlineContent":[{"text":"После успешного подключения в делегат начнут приходить сырые данные.","type":"text"}],"type":"paragraph"},{"code":["func onMEMSData(samples: [NeiryMEMSData]) {","    ","}","","func onEEGData(samples: [NeiryEEGData]) {","    ","}","","func onPPGData(samples: [NeiryPPGData]) {","    ","}"],"type":"codeListing","syntax":null},{"type":"heading","text":"Пример","level":2,"anchor":"%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80"},{"type":"paragraph","inlineContent":[{"text":"К SDK прилагается пример подключения ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","isActive":true},{"type":"text","text":". Проект называется NeiryApp. Вся работа с "},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","type":"reference","isActive":true},{"text":" происходит в классе NeiryManager.","type":"text"}]},{"text":"Делегат","level":2,"anchor":"%D0%94%D0%B5%D0%BB%D0%B5%D0%B3%D0%B0%D1%82","type":"heading"},{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onError(message:)"},{"type":"text","text":" - метод вызывается при ошибках."}],"type":"paragraph"},{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onLog(message:)","isActive":true},{"type":"text","text":" - метод вызывается когда, что-то логируется в "},{"type":"reference","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","isActive":true},{"text":". Разработчик сам может решать, что нужно логировать.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onDisconnected()","type":"reference","isActive":true},{"text":" - метод вызывается при отключении устройства.","type":"text"}]},{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onConnected(device:channels:)","isActive":true},{"text":" - метод вызывается, когда устройство подключено.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onDevices(devices:)"},{"text":" - метод вызывается когда SDK найдет список устройств.","type":"text"}]},{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onMEMSData(samples:)"},{"type":"text","text":" - метод вызывается когда с устройства приходят сырые MEMS данные."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onEEGData(samples:)","isActive":true,"type":"reference"},{"text":" - метод вызывается когда с устройства приходят сырые EEG данные.","type":"text"}]},{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onPPGData(samples:)","type":"reference","isActive":true},{"text":" - метод вызывается когда с устройства приходят сырые PPG данные.","type":"text"}]},{"inlineContent":[{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onBattery(_:)","type":"reference","isActive":true},{"type":"text","text":" - метод вызывается при изменении заряда батареи."}],"type":"paragraph"}]}],"sections":[],"topicSections":[{"title":"Classes","anchor":"Classes","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData"]},{"title":"Protocols","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate"],"anchor":"Protocols"},{"anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBMetricsProductivity","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBMetricsProductivityBaselines","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBMetricsProductivityIndividualIndexes","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBUserArtifacts","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBUserState","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Cardio","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/IndividualNFBData","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Point3d"],"title":"Structures"},{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_IDLE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_POWERDOWN","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_RESISTANCE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNAL","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNALANDRESIST","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTMEMS","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTPPG","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPMEMS","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPPPG","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_ANY","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_BUDS","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_FILE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADBAND","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADPHONES","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_IMPULSE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_LSL","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_NOISE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_SINWAVE"]},{"title":"Enumerations","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CapsuleAddress","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Emotion","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceEvent","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.enum","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceModel","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPolarMode","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/PhysiologicalStates","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/PhysiologicalStatesBaselines"],"generated":true,"anchor":"Enumerations"}],"variants":[{"paths":["\/documentation\/neirykit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/neirykit"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onConnected(device:channels:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConnected"},{"text":"(","kind":"text"},{"text":"device","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NeiryDevice","text":"NeiryDevice","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"channels","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryChannel","kind":"typeIdentifier","text":"NeiryChannel"},{"kind":"text","text":"])"}],"kind":"symbol","abstract":[],"required":true,"title":"onConnected(device:channels:)","role":"symbol","url":"\/documentation\/neirykit\/neirydelegate\/onconnected(device:channels:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onConnected(device:channels:)","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPolarMode":{"url":"\/documentation\/neirykit\/neirypolarmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryPolarMode"}],"kind":"symbol","title":"NeiryPolarMode","navigatorTitle":[{"text":"NeiryPolarMode","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPolarMode"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/create(address:name:type:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/create(address:name:type:)","abstract":[{"type":"text","text":"Функция создает и инициализирует CapsuleClient"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8NeiryKit14CapsuleAddressO","text":"CapsuleAddress"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/neirykit\/neiry\/create(address:name:type:)","type":"topic","kind":"symbol","title":"create(address:name:type:)","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onError(message:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onError(message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"onError(message:)","abstract":[],"url":"\/documentation\/neirykit\/neirydelegate\/onerror(message:)","required":true,"role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_IMPULSE":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"TYPE_IMPULSE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"}],"url":"\/documentation\/neirykit\/type_impulse","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_IMPULSE","abstract":[],"title":"TYPE_IMPULSE","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TYPE_IMPULSE","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryKitVersionString":{"abstract":[{"type":"text","text":"Project version string for NeiryKit."}],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryKitVersionString","role":"symbol","url":"\/documentation\/neirykit\/neirykitversionstring","title":"NeiryKitVersionString","kind":"symbol","fragments":[{"kind":"identifier","text":"NeiryKitVersionString"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_ANY":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TYPE_ANY"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_ANY","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"}],"title":"TYPE_ANY","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_ANY","role":"symbol","url":"\/documentation\/neirykit\/type_any"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryEEGData":{"navigatorTitle":[{"kind":"identifier","text":"NeiryEEGData"}],"role":"symbol","url":"\/documentation\/neirykit\/neiryeegdata","type":"topic","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData","abstract":[],"title":"NeiryEEGData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NeiryEEGData","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_FILE":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_FILE","role":"symbol","url":"\/documentation\/neirykit\/type_file","title":"TYPE_FILE","navigatorTitle":[{"kind":"identifier","text":"TYPE_FILE"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"TYPE_FILE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier","text":"NeiryDeviceType"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_RESISTANCE":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MODE_RESISTANCE"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"MODE_RESISTANCE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"title":"MODE_RESISTANCE","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_RESISTANCE","role":"symbol","url":"\/documentation\/neirykit\/mode_resistance"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STARTMEMS":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTMEMS","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_STARTMEMS"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier"}],"abstract":[],"title":"MODE_STARTMEMS","type":"topic","navigatorTitle":[{"text":"MODE_STARTMEMS","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/mode_startmems"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onDisconnected()":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onDisconnected","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onDisconnected()","type":"topic","required":true,"title":"onDisconnected()","kind":"symbol","url":"\/documentation\/neirykit\/neirydelegate\/ondisconnected()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Point3d":{"abstract":[{"text":"Точка","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"Point3d","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Point3d","navigatorTitle":[{"kind":"identifier","text":"Point3d"}],"url":"\/documentation\/neirykit\/point3d","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Point3d","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc":{"type":"topic","title":"NeiryClientObjc","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryClientObjc","kind":"identifier"}],"navigatorTitle":[{"text":"NeiryClientObjc","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc","url":"\/documentation\/neirykit\/neiryclientobjc"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceModel":{"type":"topic","title":"NeiryDeviceModel","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceModel"}],"abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceModel","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceModel","url":"\/documentation\/neirykit\/neirydevicemodel","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_IDLE":{"url":"\/documentation\/neirykit\/mode_idle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_IDLE"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"title":"MODE_IDLE","role":"symbol","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_IDLE","kind":"symbol","navigatorTitle":[{"text":"MODE_IDLE","kind":"identifier"}],"type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_SIGNALANDRESIST":{"url":"\/documentation\/neirykit\/mode_signalandresist","type":"topic","title":"MODE_SIGNALANDRESIST","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNALANDRESIST","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MODE_SIGNALANDRESIST"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceMode","text":"NeiryDeviceMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"MODE_SIGNALANDRESIST"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onDevices(devices:)":{"url":"\/documentation\/neirykit\/neirydelegate\/ondevices(devices:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onDevices"},{"text":"(","kind":"text"},{"text":"devices","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NeiryDevice","text":"NeiryDevice","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onDevices(devices:)","type":"topic","title":"onDevices(devices:)","abstract":[],"kind":"symbol","required":true,"role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryChannel":{"url":"\/documentation\/neirykit\/neirychannel","abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel","title":"NeiryChannel","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NeiryChannel"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryChannel"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onLog(message:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onLog"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"required":true,"title":"onLog(message:)","role":"symbol","url":"\/documentation\/neirykit\/neirydelegate\/onlog(message:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onLog(message:)","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/CNFBMetricsProductivityBaselines":{"abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CNFBMetricsProductivityBaselines"}],"role":"symbol","url":"\/documentation\/neirykit\/cnfbmetricsproductivitybaselines","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBMetricsProductivityBaselines","title":"CNFBMetricsProductivityBaselines","navigatorTitle":[{"kind":"identifier","text":"CNFBMetricsProductivityBaselines"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STOPPPG":{"role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MODE_STOPPPG"}],"type":"topic","title":"MODE_STOPPPG","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_STOPPPG"},{"kind":"text","text":": "},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPPPG","url":"\/documentation\/neirykit\/mode_stopppg"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onEEGData(samples:)":{"required":true,"kind":"symbol","abstract":[],"title":"onEEGData(samples:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onEEGData(samples:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onEEGData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"samples"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NeiryEEGData","preciseIdentifier":"c:objc(cs)NeiryEEGData"},{"text":"])","kind":"text"}],"role":"symbol","url":"\/documentation\/neirykit\/neirydelegate\/oneegdata(samples:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onBattery(_:)":{"url":"\/documentation\/neirykit\/neirydelegate\/onbattery(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onBattery","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onBattery(_:)","type":"topic","title":"onBattery(_:)","abstract":[],"kind":"symbol","required":true,"role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPPGData":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData","abstract":[],"role":"symbol","url":"\/documentation\/neirykit\/neiryppgdata","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryPPGData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryPPGData"}],"type":"topic","title":"NeiryPPGData"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate","type":"topic","navigatorTitle":[{"text":"NeiryDelegate","kind":"identifier"}],"title":"NeiryDelegate","kind":"symbol","url":"\/documentation\/neirykit\/neirydelegate"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_LSL":{"type":"topic","url":"\/documentation\/neirykit\/type_lsl","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_LSL","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TYPE_LSL","kind":"identifier"}],"title":"TYPE_LSL","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"TYPE_LSL","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType","kind":"typeIdentifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/PhysiologicalStatesBaselines":{"type":"topic","title":"PhysiologicalStatesBaselines","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/PhysiologicalStatesBaselines","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhysiologicalStatesBaselines"}],"navigatorTitle":[{"text":"PhysiologicalStatesBaselines","kind":"identifier"}],"url":"\/documentation\/neirykit\/physiologicalstatesbaselines","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/IndividualNFBData":{"title":"IndividualNFBData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IndividualNFBData"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/IndividualNFBData","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IndividualNFBData"}],"url":"\/documentation\/neirykit\/individualnfbdata"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2":{"url":"\/documentation\/neirykit\/neirydevicetype2","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType2"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"NeiryDeviceType2"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onPPGData(samples:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPPGData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"samples"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NeiryPPGData","preciseIdentifier":"c:objc(cs)NeiryPPGData"},{"text":"])","kind":"text"}],"kind":"symbol","abstract":[],"required":true,"title":"onPPGData(samples:)","role":"symbol","url":"\/documentation\/neirykit\/neirydelegate\/onppgdata(samples:)","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onPPGData(samples:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/CNFBMetricsProductivityIndividualIndexes":{"abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CNFBMetricsProductivityIndividualIndexes"}],"navigatorTitle":[{"kind":"identifier","text":"CNFBMetricsProductivityIndividualIndexes"}],"url":"\/documentation\/neirykit\/cnfbmetricsproductivityindividualindexes","kind":"symbol","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBMetricsProductivityIndividualIndexes","title":"CNFBMetricsProductivityIndividualIndexes"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_SINWAVE":{"title":"TYPE_SINWAVE","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_SINWAVE","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_SINWAVE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"}],"url":"\/documentation\/neirykit\/type_sinwave","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TYPE_SINWAVE"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STOPMEMS":{"kind":"symbol","url":"\/documentation\/neirykit\/mode_stopmems","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_STOPMEMS","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceMode","text":"NeiryDeviceMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"MODE_STOPMEMS"}],"title":"MODE_STOPMEMS","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPMEMS","type":"topic","abstract":[],"role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","title":"NeiryClientObjcDelegate","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"type":"topic","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryKitVersionNumber":{"abstract":[{"text":"Project version number for NeiryKit.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryKitVersionNumber","role":"symbol","url":"\/documentation\/neirykit\/neirykitversionnumber","title":"NeiryKitVersionNumber","kind":"symbol","fragments":[{"text":"NeiryKitVersionNumber","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_SIGNAL":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_SIGNAL","kind":"identifier"},{"kind":"text","text":": "},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"role":"symbol","title":"MODE_SIGNAL","url":"\/documentation\/neirykit\/mode_signal","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MODE_SIGNAL"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNAL"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/PhysiologicalStates":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PhysiologicalStates","kind":"identifier"}],"role":"symbol","title":"PhysiologicalStates","url":"\/documentation\/neirykit\/physiologicalstates","abstract":[],"type":"topic","navigatorTitle":[{"text":"PhysiologicalStates","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/PhysiologicalStates"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/CapsuleAddress":{"title":"CapsuleAddress","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CapsuleAddress"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CapsuleAddress","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CapsuleAddress","url":"\/documentation\/neirykit\/capsuleaddress","abstract":[],"type":"topic","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Emotion":{"url":"\/documentation\/neirykit\/emotion","navigatorTitle":[{"kind":"identifier","text":"Emotion"}],"abstract":[],"title":"Emotion","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Emotion","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Emotion"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_POWERDOWN":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_POWERDOWN","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_POWERDOWN"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier","text":"NeiryDeviceMode"}],"title":"MODE_POWERDOWN","url":"\/documentation\/neirykit\/mode_powerdown","abstract":[],"type":"topic","navigatorTitle":[{"text":"MODE_POWERDOWN","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_HEADBAND":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TYPE_HEADBAND"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType"}],"url":"\/documentation\/neirykit\/type_headband","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADBAND","navigatorTitle":[{"text":"TYPE_HEADBAND","kind":"identifier"}],"title":"TYPE_HEADBAND","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onMEMSData(samples:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMEMSData","kind":"identifier"},{"kind":"text","text":"("},{"text":"samples","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NeiryMEMSData","preciseIdentifier":"c:objc(cs)NeiryMEMSData","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onMEMSData(samples:)","abstract":[],"url":"\/documentation\/neirykit\/neirydelegate\/onmemsdata(samples:)","title":"onMEMSData(samples:)","required":true,"type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STARTPPG":{"title":"MODE_STARTPPG","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTPPG","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_STARTPPG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/mode_startppg","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MODE_STARTPPG"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/requestDevices()":{"abstract":[{"type":"text","text":"Запрашиваем список устройств"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/requestDevices()","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiry\/requestdevices()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestDevices","kind":"identifier"},{"text":"()","kind":"text"}],"title":"requestDevices()","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_HEADPHONES":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/neirykit\/type_headphones","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADPHONES","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_HEADPHONES","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"TYPE_HEADPHONES","kind":"identifier"}],"title":"TYPE_HEADPHONES","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/CNFBMetricsProductivity":{"title":"CNFBMetricsProductivity","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CNFBMetricsProductivity"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBMetricsProductivity","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CNFBMetricsProductivity"}],"role":"symbol","url":"\/documentation\/neirykit\/cnfbmetricsproductivity","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Cardio":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Cardio","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Cardio","kind":"identifier"}],"title":"Cardio","type":"topic","role":"symbol","navigatorTitle":[{"text":"Cardio","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/neirykit\/cardio"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.enum":{"url":"\/documentation\/neirykit\/neirydevicemode-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}],"kind":"symbol","title":"NeiryDeviceMode","role":"symbol","type":"topic","navigatorTitle":[{"text":"NeiryDeviceMode","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.enum"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/CNFBUserArtifacts":{"title":"CNFBUserArtifacts","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBUserArtifacts","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CNFBUserArtifacts","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/cnfbuserartifacts","type":"topic","abstract":[],"navigatorTitle":[{"text":"CNFBUserArtifacts","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_NOISE":{"title":"TYPE_NOISE","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_NOISE","url":"\/documentation\/neirykit\/type_noise","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_NOISE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType"}],"navigatorTitle":[{"text":"TYPE_NOISE","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_BUDS":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/neirykit\/type_buds","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_BUDS","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TYPE_BUDS","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"TYPE_BUDS"}],"title":"TYPE_BUDS","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDevice":{"abstract":[],"title":"NeiryDevice","navigatorTitle":[{"text":"NeiryDevice","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDevice"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neirydevice"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/CNFBUserState":{"abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CNFBUserState","kind":"identifier"}],"url":"\/documentation\/neirykit\/cnfbuserstate","role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CNFBUserState","kind":"symbol","title":"CNFBUserState","navigatorTitle":[{"kind":"identifier","text":"CNFBUserState"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceEvent":{"role":"symbol","kind":"symbol","title":"NeiryDeviceEvent","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceEvent","kind":"identifier"}],"url":"\/documentation\/neirykit\/neirydeviceevent","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceEvent"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NeiryMEMSData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryMEMSData"}],"url":"\/documentation\/neirykit\/neirymemsdata","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","title":"NeiryMEMSData"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData"],"anchor":"Classes"},{"anchor":"Protocols","title":"Protocols","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate"]},{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryKitVersionNumber","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryKitVersionString"],"title":"Variables","anchor":"Variables","generated":true},{"generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2"],"title":"Enumerations","anchor":"Enumerations"}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"TYPE_IMPULSE","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_IMPULSE\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_IMPULSE\/fragments","value":[{"kind":"identifier","text":"TYPE_IMPULSE"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_ANY\/title","value":"TYPE_ANY"},{"value":[{"text":"TYPE_ANY","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_ANY\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/title","value":"NeiryEEGData","op":"replace"},{"op":"replace","value":[{"text":"NeiryEEGData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/navigatorTitle","op":"replace","value":[{"text":"NeiryEEGData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_FILE\/title","op":"replace","value":"TYPE_FILE"},{"value":[{"kind":"identifier","text":"TYPE_FILE"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_FILE\/fragments","op":"replace"},{"value":"MODE_RESISTANCE","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_RESISTANCE\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MODE_RESISTANCE"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_RESISTANCE\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTMEMS\/title","op":"replace","value":"MODE_STARTMEMS"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTMEMS\/fragments","value":[{"kind":"identifier","text":"MODE_STARTMEMS"}]},{"op":"replace","value":"NeiryClientObjc","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/fragments","op":"replace","value":[{"kind":"identifier","text":"NeiryClientObjc"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/navigatorTitle","value":[{"text":"NeiryClientObjc","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_IDLE\/title","op":"replace","value":"MODE_IDLE"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_IDLE\/fragments","op":"replace","value":[{"text":"MODE_IDLE","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNALANDRESIST\/title","value":"MODE_SIGNALANDRESIST","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNALANDRESIST\/fragments","value":[{"text":"MODE_SIGNALANDRESIST","kind":"identifier"}]},{"value":"Neiry","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments","op":"replace","value":[{"kind":"identifier","text":"Neiry"}]},{"value":[{"text":"Neiry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle","op":"replace"},{"value":"NeiryChannel","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/fragments","value":[{"text":"NeiryChannel","kind":"identifier"}]},{"op":"replace","value":[{"text":"NeiryChannel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPPPG\/title","value":"MODE_STOPPPG"},{"op":"replace","value":[{"text":"MODE_STOPPPG","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPPPG\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/title","value":"NeiryPPGData"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/fragments","op":"replace","value":[{"text":"NeiryPPGData","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NeiryPPGData"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/navigatorTitle"},{"value":"TYPE_LSL","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_LSL\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_LSL\/fragments","value":[{"text":"TYPE_LSL","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"NeiryDeviceType","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryDeviceType"}]},{"value":"NeiryDeviceType2","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/fragments","value":[{"kind":"identifier","text":"NeiryDeviceType2"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryDeviceType2"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_SINWAVE\/title","value":"TYPE_SINWAVE"},{"value":[{"kind":"identifier","text":"TYPE_SINWAVE"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_SINWAVE\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPMEMS\/title","value":"MODE_STOPMEMS","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPMEMS\/fragments","op":"replace","value":[{"text":"MODE_STOPMEMS","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/title","op":"replace","value":"NeiryClientObjcDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/fragments","value":[{"text":"NeiryClientObjcDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/navigatorTitle","op":"replace"},{"op":"replace","value":"MODE_SIGNAL","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNAL\/title"},{"value":[{"text":"MODE_SIGNAL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNAL\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_POWERDOWN\/title","value":"MODE_POWERDOWN","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_POWERDOWN\/fragments","value":[{"text":"MODE_POWERDOWN","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADBAND\/title","value":"TYPE_HEADBAND"},{"op":"replace","value":[{"text":"TYPE_HEADBAND","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADBAND\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title","value":"NeiryDeviceMode"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments","value":[{"text":"NeiryDeviceMode","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle"},{"value":"MODE_STARTPPG","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTPPG\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MODE_STARTPPG"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTPPG\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADPHONES\/title","op":"replace","value":"TYPE_HEADPHONES"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADPHONES\/fragments","op":"replace","value":[{"text":"TYPE_HEADPHONES","kind":"identifier"}]},{"value":"TYPE_NOISE","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_NOISE\/title","op":"replace"},{"value":[{"text":"TYPE_NOISE","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_NOISE\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_BUDS\/title","value":"TYPE_BUDS"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_BUDS\/fragments","value":[{"text":"TYPE_BUDS","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/title","value":"NeiryDevice","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/fragments","op":"replace","value":[{"kind":"identifier","text":"NeiryDevice"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NeiryDevice"}]},{"value":"NeiryMEMSData","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/fragments","op":"replace","value":[{"text":"NeiryMEMSData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/navigatorTitle","value":[{"text":"NeiryMEMSData","kind":"identifier"}],"op":"replace"}]}]}