{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConnected"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"device"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryDevice","text":"NeiryDevice"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channels"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryChannel","text":"NeiryChannel","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"roleHeading":"Instance Method","required":true,"role":"symbol","externalID":"s:8NeiryKit0A8DelegateP11onConnected6device8channelsySo0A6DeviceC_SaySo0A7ChannelCGtF","symbolKind":"method","title":"onConnected(device:channels:)","modules":[{"name":"NeiryKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onConnected(device:channels:)"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydelegate\/onconnected(device:channels:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConnected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"device","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryDevice","kind":"typeIdentifier","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","text":"NeiryDevice"},{"text":", ","kind":"text"},{"text":"channels","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NeiryChannel","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel","preciseIdentifier":"c:objc(cs)NeiryChannel","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onConnected(device:channels:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConnected"},{"text":"(","kind":"text"},{"text":"device","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NeiryDevice","text":"NeiryDevice","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"channels","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryChannel","kind":"typeIdentifier","text":"NeiryChannel"},{"kind":"text","text":"])"}],"kind":"symbol","abstract":[],"required":true,"title":"onConnected(device:channels:)","role":"symbol","url":"\/documentation\/neirykit\/neirydelegate\/onconnected(device:channels:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onConnected(device:channels:)","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDevice":{"abstract":[],"title":"NeiryDevice","navigatorTitle":[{"text":"NeiryDevice","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDevice"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neirydevice"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate","type":"topic","navigatorTitle":[{"text":"NeiryDelegate","kind":"identifier"}],"title":"NeiryDelegate","kind":"symbol","url":"\/documentation\/neirykit\/neirydelegate"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryChannel":{"url":"\/documentation\/neirykit\/neirychannel","abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel","title":"NeiryChannel","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NeiryChannel"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryChannel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/title","value":"NeiryDevice"},{"value":[{"text":"NeiryDevice","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/navigatorTitle","value":[{"text":"NeiryDevice","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"NeiryChannel","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/fragments","op":"replace","value":[{"text":"NeiryChannel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/navigatorTitle","op":"replace","value":[{"text":"NeiryChannel","kind":"identifier"}]}]}]}