{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onDevices(devices:)"},"metadata":{"modules":[{"name":"NeiryKit"}],"title":"onDevices(devices:)","role":"symbol","externalID":"s:8NeiryKit0A8DelegateP9onDevices7devicesySaySo0A6DeviceCG_tF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onDevices","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"devices"},{"text":": [","kind":"text"},{"text":"NeiryDevice","preciseIdentifier":"c:objc(cs)NeiryDevice","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"required":true,"symbolKind":"method","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDevices"},{"text":"(","kind":"text"},{"text":"devices","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NeiryDevice","preciseIdentifier":"c:objc(cs)NeiryDevice","kind":"typeIdentifier","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice"},{"kind":"text","text":"])"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydelegate\/ondevices(devices:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDevice":{"abstract":[],"title":"NeiryDevice","navigatorTitle":[{"text":"NeiryDevice","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDevice"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neirydevice"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onDevices(devices:)":{"url":"\/documentation\/neirykit\/neirydelegate\/ondevices(devices:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onDevices"},{"text":"(","kind":"text"},{"text":"devices","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NeiryDevice","text":"NeiryDevice","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onDevices(devices:)","type":"topic","title":"onDevices(devices:)","abstract":[],"kind":"symbol","required":true,"role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate","type":"topic","navigatorTitle":[{"text":"NeiryDelegate","kind":"identifier"}],"title":"NeiryDelegate","kind":"symbol","url":"\/documentation\/neirykit\/neirydelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/title","value":"NeiryDevice","op":"replace"},{"value":[{"text":"NeiryDevice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/navigatorTitle","value":[{"text":"NeiryDevice","kind":"identifier"}]}]}]}