{"kind":"symbol","variants":[{"paths":["\/documentation\/neirykit\/neirydelegate\/oneegdata(samples:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onEEGData(samples:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onEEGData","kind":"identifier"},{"kind":"text","text":"("},{"text":"samples","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryEEGData","text":"NeiryEEGData"},{"text":"])","kind":"text"}]}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onEEGData","kind":"identifier"},{"kind":"text","text":"("},{"text":"samples","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"NeiryEEGData","preciseIdentifier":"c:objc(cs)NeiryEEGData","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"modules":[{"name":"NeiryKit"}],"externalID":"s:8NeiryKit0A8DelegateP9onEEGData7samplesySaySo0aE0CG_tF","title":"onEEGData(samples:)","roleHeading":"Instance Method","symbolKind":"method","required":true,"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate","type":"topic","navigatorTitle":[{"text":"NeiryDelegate","kind":"identifier"}],"title":"NeiryDelegate","kind":"symbol","url":"\/documentation\/neirykit\/neirydelegate"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onEEGData(samples:)":{"required":true,"kind":"symbol","abstract":[],"title":"onEEGData(samples:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onEEGData(samples:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onEEGData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"samples"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NeiryEEGData","preciseIdentifier":"c:objc(cs)NeiryEEGData"},{"text":"])","kind":"text"}],"role":"symbol","url":"\/documentation\/neirykit\/neirydelegate\/oneegdata(samples:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryEEGData":{"navigatorTitle":[{"kind":"identifier","text":"NeiryEEGData"}],"role":"symbol","url":"\/documentation\/neirykit\/neiryeegdata","type":"topic","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData","abstract":[],"title":"NeiryEEGData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NeiryEEGData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/title","op":"replace","value":"NeiryEEGData"},{"op":"replace","value":[{"text":"NeiryEEGData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/fragments"},{"value":[{"text":"NeiryEEGData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/navigatorTitle"}]}]}