{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMEMSData"},{"text":"(","kind":"text"},{"text":"samples","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryMEMSData","text":"NeiryMEMSData"},{"kind":"text","text":"])"}],"role":"symbol","required":true,"roleHeading":"Instance Method","externalID":"s:8NeiryKit0A8DelegateP10onMEMSData7samplesySaySo0aE0CG_tF","symbolKind":"method","title":"onMEMSData(samples:)","modules":[{"name":"NeiryKit"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onMEMSData(samples:)"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMEMSData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"samples","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","preciseIdentifier":"c:objc(cs)NeiryMEMSData","text":"NeiryMEMSData"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/neirykit\/neirydelegate\/onmemsdata(samples:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate","type":"topic","navigatorTitle":[{"text":"NeiryDelegate","kind":"identifier"}],"title":"NeiryDelegate","kind":"symbol","url":"\/documentation\/neirykit\/neirydelegate"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NeiryMEMSData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryMEMSData"}],"url":"\/documentation\/neirykit\/neirymemsdata","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","title":"NeiryMEMSData"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onMEMSData(samples:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMEMSData","kind":"identifier"},{"kind":"text","text":"("},{"text":"samples","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NeiryMEMSData","preciseIdentifier":"c:objc(cs)NeiryMEMSData","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onMEMSData(samples:)","abstract":[],"url":"\/documentation\/neirykit\/neirydelegate\/onmemsdata(samples:)","title":"onMEMSData(samples:)","required":true,"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/title","op":"replace","value":"NeiryMEMSData"},{"value":[{"text":"NeiryMEMSData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/navigatorTitle","op":"replace","value":[{"text":"NeiryMEMSData","kind":"identifier"}]}]}]}