{"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPPGData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"samples","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryPPGData","text":"NeiryPPGData"},{"text":"])","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","required":true,"externalID":"s:8NeiryKit0A8DelegateP9onPPGData7samplesySaySo0aE0CG_tF","symbolKind":"method","title":"onPPGData(samples:)","modules":[{"name":"NeiryKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPPGData"},{"kind":"text","text":"("},{"text":"samples","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NeiryPPGData","text":"NeiryPPGData","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onPPGData(samples:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydelegate\/onppgdata(samples:)"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate","type":"topic","navigatorTitle":[{"text":"NeiryDelegate","kind":"identifier"}],"title":"NeiryDelegate","kind":"symbol","url":"\/documentation\/neirykit\/neirydelegate"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDelegate/onPPGData(samples:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPPGData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"samples"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NeiryPPGData","preciseIdentifier":"c:objc(cs)NeiryPPGData"},{"text":"])","kind":"text"}],"kind":"symbol","abstract":[],"required":true,"title":"onPPGData(samples:)","role":"symbol","url":"\/documentation\/neirykit\/neirydelegate\/onppgdata(samples:)","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDelegate\/onPPGData(samples:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPPGData":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData","abstract":[],"role":"symbol","url":"\/documentation\/neirykit\/neiryppgdata","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryPPGData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryPPGData"}],"type":"topic","title":"NeiryPPGData"}},"variantOverrides":[{"patch":[{"value":"NeiryPPGData","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/fragments","value":[{"kind":"identifier","text":"NeiryPPGData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryPPGData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}