{"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier","text":"NeiryDeviceType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/neirykit\/neirydevice\/devicetype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neirydevice\/devicetype"]}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceType"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"}],"role":"symbol","title":"deviceType","roleHeading":"Instance Property","navigatorTitle":[{"text":"deviceType","kind":"identifier"}],"externalID":"c:objc(cs)NeiryDevice(py)deviceType","modules":[{"name":"NeiryKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice\/deviceType"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDevice/deviceType":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/neirykit\/neirydevice\/devicetype","navigatorTitle":[{"kind":"identifier","text":"deviceType"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice\/deviceType","title":"deviceType"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDevice":{"abstract":[],"title":"NeiryDevice","navigatorTitle":[{"text":"NeiryDevice","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDevice"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neirydevice"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"deviceType","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"deviceType"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"NeiryDeviceType","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title"},{"op":"replace","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments"},{"value":[{"kind":"identifier","text":"NeiryDeviceType"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","op":"replace"},{"op":"replace","value":"deviceType","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice~1deviceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice~1deviceType\/fragments","value":[{"text":"deviceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/title","value":"NeiryDevice"},{"value":[{"kind":"identifier","text":"NeiryDevice"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryDevice"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}