{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceMode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:objc(cs)NeiryDevice(py)deviceMode","title":"deviceMode","symbolKind":"property","modules":[{"name":"NeiryKit"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"deviceMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"navigatorTitle":[{"text":"deviceMode","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice\/deviceMode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevice\/devicemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neirydevice\/devicemode"]}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDevice/deviceMode":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice\/deviceMode","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neirydevice\/devicemode","navigatorTitle":[{"text":"deviceMode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"deviceMode"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDevice":{"abstract":[],"title":"NeiryDevice","navigatorTitle":[{"text":"NeiryDevice","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDevice"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neirydevice"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"deviceMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"deviceMode","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct"},{"kind":"text","text":" "},{"text":"deviceMode","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title","value":"NeiryDeviceMode","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments","op":"replace","value":[{"text":"NeiryDeviceMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice~1deviceMode\/title","value":"deviceMode","op":"replace"},{"value":[{"text":"deviceMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice~1deviceMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/title","op":"replace","value":"NeiryDevice"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/fragments","value":[{"text":"NeiryDevice","kind":"identifier"}]},{"value":[{"text":"NeiryDevice","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}