{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MODE_STARTPPG"}],"modules":[{"name":"NeiryKit"}],"roleHeading":"Global Variable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_STARTPPG","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier","text":"NeiryDeviceMode"}],"symbolKind":"var","title":"MODE_STARTPPG","role":"symbol","externalID":"c:@E@NeiryDeviceMode@MODE_STARTPPG"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_STARTPPG","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","text":"NeiryDeviceMode"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTPPG"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/mode_startppg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/mode_startppg"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STARTPPG":{"title":"MODE_STARTPPG","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTPPG","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_STARTPPG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/mode_startppg","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MODE_STARTPPG"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MODE_STARTPPG"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MODE_STARTPPG","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MODE_STARTPPG","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MODE_STARTPPG","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTPPG\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTPPG\/fragments","value":[{"text":"MODE_STARTPPG","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title","op":"replace","value":"NeiryDeviceMode"},{"value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceMode"}]}]}]}