{"sections":[],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MODE_SIGNALANDRESIST"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"title":"MODE_SIGNALANDRESIST","symbolKind":"var","modules":[{"name":"NeiryKit"}],"navigatorTitle":[{"kind":"identifier","text":"MODE_SIGNALANDRESIST"}],"externalID":"c:@E@NeiryDeviceMode@MODE_SIGNALANDRESIST","roleHeading":"Global Variable"},"variants":[{"paths":["\/documentation\/neirykit\/mode_signalandresist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/neirykit\/mode_signalandresist"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNALANDRESIST"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"MODE_SIGNALANDRESIST","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_SIGNALANDRESIST":{"url":"\/documentation\/neirykit\/mode_signalandresist","type":"topic","title":"MODE_SIGNALANDRESIST","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNALANDRESIST","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MODE_SIGNALANDRESIST"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceMode","text":"NeiryDeviceMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"MODE_SIGNALANDRESIST"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MODE_SIGNALANDRESIST","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MODE_SIGNALANDRESIST"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"MODE_SIGNALANDRESIST","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNALANDRESIST\/title","value":"MODE_SIGNALANDRESIST","op":"replace"},{"value":[{"text":"MODE_SIGNALANDRESIST","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNALANDRESIST\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title","value":"NeiryDeviceMode"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments","value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle"}]}]}