{"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPMEMS","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MODE_STOPMEMS"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"MODE_STOPMEMS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceMode","text":"NeiryDeviceMode","kind":"typeIdentifier"}],"role":"symbol","title":"MODE_STOPMEMS","externalID":"c:@E@NeiryDeviceMode@MODE_STOPMEMS","symbolKind":"var","roleHeading":"Global Variable","navigatorTitle":[{"text":"MODE_STOPMEMS","kind":"identifier"}],"modules":[{"name":"NeiryKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct"]]},"variants":[{"paths":["\/documentation\/neirykit\/mode_stopmems"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/mode_stopmems"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STOPMEMS":{"kind":"symbol","url":"\/documentation\/neirykit\/mode_stopmems","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_STOPMEMS","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceMode","text":"NeiryDeviceMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"MODE_STOPMEMS"}],"title":"MODE_STOPMEMS","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPMEMS","type":"topic","abstract":[],"role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"kind":"symbol","title":"NeiryKit","abstract":[],"role":"collection","url":"\/documentation\/neirykit","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MODE_STOPMEMS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MODE_STOPMEMS","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MODE_STOPMEMS"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"NeiryDeviceMode","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title"},{"value":[{"text":"NeiryDeviceMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPMEMS\/title","op":"replace","value":"MODE_STOPMEMS"},{"value":[{"text":"MODE_STOPMEMS","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPMEMS\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}