{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/mode_startmems"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/mode_startmems"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MODE_STARTMEMS"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode","text":"NeiryDeviceMode"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct"]]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTMEMS","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"NeiryKit"}],"title":"MODE_STARTMEMS","role":"symbol","symbolKind":"var","roleHeading":"Global Variable","externalID":"c:@E@NeiryDeviceMode@MODE_STARTMEMS","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"MODE_STARTMEMS","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"navigatorTitle":[{"text":"MODE_STARTMEMS","kind":"identifier"}]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STARTMEMS":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTMEMS","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_STARTMEMS"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier"}],"abstract":[],"title":"MODE_STARTMEMS","type":"topic","navigatorTitle":[{"text":"MODE_STARTMEMS","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/mode_startmems"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MODE_STARTMEMS"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MODE_STARTMEMS","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MODE_STARTMEMS","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title","value":"NeiryDeviceMode","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments","value":[{"text":"NeiryDeviceMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceMode"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTMEMS\/title","op":"replace","value":"MODE_STARTMEMS"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTMEMS\/fragments","value":[{"kind":"identifier","text":"MODE_STARTMEMS"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}