{"metadata":{"roleHeading":"Enumeration","title":"NeiryDeviceType2","externalID":"c:@M@NeiryKit@E@NeiryDeviceType2","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceType2","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType2"}],"modules":[{"name":"NeiryKit"}],"role":"symbol","symbolKind":"enum"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType2"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/any","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/buds","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/file","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/headband","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/headphones","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/impulse","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/lsl","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/noise","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/sinwave","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/undefined"],"generated":true,"anchor":"Enumeration-Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/getName()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/Equatable-Implementations","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicetype2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neirydevicetype2"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.asinenko.NeiryKit\/SQ","doc:\/\/com.asinenko.NeiryKit\/SH","doc:\/\/com.asinenko.NeiryKit\/SY"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2":{"url":"\/documentation\/neirykit\/neirydevicetype2","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType2"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"NeiryDeviceType2"},"doc://com.asinenko.NeiryKit/SQ":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/undefined":{"title":"NeiryDeviceType2.undefined","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/undefined","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/neirydevicetype2\/undefined","type":"topic","abstract":[],"navigatorTitle":[{"text":"NeiryDeviceType2Undefined","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/noise":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/noise","title":"NeiryDeviceType2.noise","url":"\/documentation\/neirykit\/neirydevicetype2\/noise","abstract":[],"navigatorTitle":[{"text":"NeiryDeviceType2Noise","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noise"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/buds":{"kind":"symbol","role":"symbol","title":"NeiryDeviceType2.buds","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType2Buds"}],"url":"\/documentation\/neirykit\/neirydevicetype2\/buds","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/buds","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"buds","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/any":{"title":"NeiryDeviceType2.any","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/any","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"any","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/neirydevicetype2\/any","type":"topic","abstract":[],"navigatorTitle":[{"text":"NeiryDeviceType2Any","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/headphones":{"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"headphones","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/headphones","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2Headphones","kind":"identifier"}],"title":"NeiryDeviceType2.headphones","kind":"symbol","url":"\/documentation\/neirykit\/neirydevicetype2\/headphones"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/impulse":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/impulse","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neirydevicetype2\/impulse","navigatorTitle":[{"text":"NeiryDeviceType2Impulse","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"impulse"}],"kind":"symbol","role":"symbol","title":"NeiryDeviceType2.impulse"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/sinwave":{"role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"NeiryDeviceType2Sinwave","kind":"identifier"}],"title":"NeiryDeviceType2.sinwave","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sinwave","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/sinwave","url":"\/documentation\/neirykit\/neirydevicetype2\/sinwave"},"doc://com.asinenko.NeiryKit/SH":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.asinenko.NeiryKit/SY":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/file":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/file","url":"\/documentation\/neirykit\/neirydevicetype2\/file","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"file","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType2File"}],"title":"NeiryDeviceType2.file","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/getName()":{"url":"\/documentation\/neirykit\/neirydevicetype2\/getname()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/getName()","title":"getName()","abstract":[],"kind":"symbol","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/headband":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/headband","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"headband","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType2Headband"}],"kind":"symbol","abstract":[],"title":"NeiryDeviceType2.headband","role":"symbol","url":"\/documentation\/neirykit\/neirydevicetype2\/headband"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/RawRepresentable-Implementations":{"type":"topic","abstract":[],"kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/neirykit\/neirydevicetype2\/rawrepresentable-implementations"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/Equatable-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/neirykit\/neirydevicetype2\/equatable-implementations"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/lsl":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/lsl","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neirydevicetype2\/lsl","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType2Lsl"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lsl","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"NeiryDeviceType2.lsl"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/init(rawValue:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/init(rawValue:)","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neirydevicetype2\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","title":"init(rawValue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"NeiryDeviceType2","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NeiryDeviceType2"}]},{"op":"replace","value":[{"text":"NeiryDeviceType2","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/any","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/buds","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/file","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/headband","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/headphones","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/impulse","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/lsl","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/noise","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/sinwave","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/undefined"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceType2","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/title","value":"NeiryDeviceType2"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/fragments","value":[{"text":"NeiryDeviceType2","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/navigatorTitle","value":[{"text":"NeiryDeviceType2","kind":"identifier"}]},{"value":"NeiryDeviceType2Undefined","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1undefined\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1undefined\/fragments","value":[{"text":"NeiryDeviceType2Undefined","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1noise\/title","value":"NeiryDeviceType2Noise"},{"op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceType2Noise"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1noise\/fragments"},{"value":"NeiryDeviceType2Buds","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1buds\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1buds\/fragments","value":[{"text":"NeiryDeviceType2Buds","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1any\/title","value":"NeiryDeviceType2Any"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1any\/fragments","value":[{"kind":"identifier","text":"NeiryDeviceType2Any"}]},{"value":"NeiryDeviceType2Headphones","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1headphones\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1headphones\/fragments","op":"replace","value":[{"text":"NeiryDeviceType2Headphones","kind":"identifier"}]},{"op":"replace","value":"NeiryDeviceType2Impulse","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1impulse\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1impulse\/fragments","value":[{"text":"NeiryDeviceType2Impulse","kind":"identifier"}]},{"value":"NeiryDeviceType2Sinwave","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1sinwave\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1sinwave\/fragments","op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceType2Sinwave"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1file\/title","value":"NeiryDeviceType2File","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1file\/fragments","value":[{"kind":"identifier","text":"NeiryDeviceType2File"}],"op":"replace"},{"value":"NeiryDeviceType2Headband","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1headband\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1headband\/fragments","value":[{"text":"NeiryDeviceType2Headband","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1lsl\/title","value":"NeiryDeviceType2Lsl","op":"replace"},{"value":[{"text":"NeiryDeviceType2Lsl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1lsl\/fragments"}]}]}