{"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.asinenko.NeiryKit\/s15BitwiseCopyableP","doc:\/\/com.asinenko.NeiryKit\/SQ","doc:\/\/com.asinenko.NeiryKit\/SY","doc:\/\/com.asinenko.NeiryKit\/s8SendableP"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicetype"]},{"paths":["\/documentation\/neirykit\/neirydevicetype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"metadata":{"externalID":"c:@E@NeiryDeviceType","role":"symbol","roleHeading":"Structure","modules":[{"name":"NeiryKit"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceType","kind":"identifier"}],"navigatorTitle":[{"text":"NeiryDeviceType","kind":"identifier"}],"symbolKind":"struct","title":"NeiryDeviceType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType\/init(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType\/rawValue"],"generated":true},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType\/Equatable-Implementations"],"anchor":"Default-Implementations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_LSL":{"type":"topic","url":"\/documentation\/neirykit\/type_lsl","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_LSL","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TYPE_LSL","kind":"identifier"}],"title":"TYPE_LSL","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"TYPE_LSL","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType","kind":"typeIdentifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType/init(rawValue:)":{"abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":")","kind":"text"}],"url":"\/documentation\/neirykit\/neirydevicetype\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType\/init(rawValue:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_ANY":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TYPE_ANY"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_ANY","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"}],"title":"TYPE_ANY","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_ANY","role":"symbol","url":"\/documentation\/neirykit\/type_any"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType/init(_:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType\/init(_:)","type":"topic","title":"init(_:)","kind":"symbol","url":"\/documentation\/neirykit\/neirydevicetype\/init(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_NOISE":{"title":"TYPE_NOISE","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_NOISE","url":"\/documentation\/neirykit\/type_noise","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_NOISE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType"}],"navigatorTitle":[{"text":"TYPE_NOISE","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_FILE":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_FILE","role":"symbol","url":"\/documentation\/neirykit\/type_file","title":"TYPE_FILE","navigatorTitle":[{"kind":"identifier","text":"TYPE_FILE"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"TYPE_FILE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier","text":"NeiryDeviceType"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_BUDS":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/neirykit\/type_buds","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_BUDS","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TYPE_BUDS","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"TYPE_BUDS"}],"title":"TYPE_BUDS","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_SINWAVE":{"title":"TYPE_SINWAVE","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_SINWAVE","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_SINWAVE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"}],"url":"\/documentation\/neirykit\/type_sinwave","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TYPE_SINWAVE"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType/rawValue":{"title":"rawValue","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType\/rawValue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/neirydevicetype\/rawvalue","type":"topic","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_HEADPHONES":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/neirykit\/type_headphones","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADPHONES","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_HEADPHONES","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"TYPE_HEADPHONES","kind":"identifier"}],"title":"TYPE_HEADPHONES","abstract":[]},"doc://com.asinenko.NeiryKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s8SendableP"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_IMPULSE":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"TYPE_IMPULSE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"}],"url":"\/documentation\/neirykit\/type_impulse","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_IMPULSE","abstract":[],"title":"TYPE_IMPULSE","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TYPE_IMPULSE","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SQ"},"doc://com.asinenko.NeiryKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SY"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_HEADBAND":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TYPE_HEADBAND"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType"}],"url":"\/documentation\/neirykit\/type_headband","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADBAND","navigatorTitle":[{"text":"TYPE_HEADBAND","kind":"identifier"}],"title":"TYPE_HEADBAND","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType/Equatable-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/neirykit\/neirydevicetype\/equatable-implementations","type":"topic","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType\/Equatable-Implementations"},"doc://com.asinenko.NeiryKit/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s15BitwiseCopyableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"NeiryDeviceType"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryDeviceType"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_ANY","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_BUDS","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_FILE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADBAND","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADPHONES","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_IMPULSE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_LSL","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_NOISE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_SINWAVE"],"generated":true}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NeiryDeviceType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" { ... } "},{"kind":"identifier","text":"NeiryDeviceType"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_LSL\/title","value":"TYPE_LSL"},{"value":[{"text":"TYPE_LSL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_LSL\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_ANY\/title","value":"TYPE_ANY"},{"op":"replace","value":[{"text":"TYPE_ANY","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_ANY\/fragments"},{"value":"TYPE_NOISE","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_NOISE\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_NOISE\/fragments","value":[{"kind":"identifier","text":"TYPE_NOISE"}]},{"value":"TYPE_FILE","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_FILE\/title"},{"op":"replace","value":[{"text":"TYPE_FILE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_FILE\/fragments"},{"value":"TYPE_BUDS","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_BUDS\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_BUDS\/fragments","value":[{"text":"TYPE_BUDS","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_SINWAVE\/title","value":"TYPE_SINWAVE"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_SINWAVE\/fragments","value":[{"kind":"identifier","text":"TYPE_SINWAVE"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADPHONES\/title","op":"replace","value":"TYPE_HEADPHONES"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADPHONES\/fragments","value":[{"kind":"identifier","text":"TYPE_HEADPHONES"}]},{"value":"TYPE_IMPULSE","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_IMPULSE\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_IMPULSE\/fragments","value":[{"text":"TYPE_IMPULSE","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title","op":"replace","value":"NeiryDeviceType"},{"op":"replace","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TYPE_HEADBAND","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADBAND\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADBAND\/fragments","value":[{"text":"TYPE_HEADBAND","kind":"identifier"}],"op":"replace"}]}]}