{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"NeiryDeviceMode","kind":"identifier"}],"symbolKind":"struct","title":"NeiryDeviceMode","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"NeiryDeviceMode","kind":"identifier"}],"externalID":"c:@E@NeiryDeviceMode","roleHeading":"Structure","modules":[{"name":"NeiryKit"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/init(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/init(rawValue:)"]},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/rawValue"],"title":"Instance Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/Equatable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/s15BitwiseCopyableP","doc:\/\/com.asinenko.NeiryKit\/SQ","doc:\/\/com.asinenko.NeiryKit\/SY","doc:\/\/com.asinenko.NeiryKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicemode-swift.struct"]},{"paths":["\/documentation\/neirykit\/neirydevicemode-swift.struct"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","interfaceLanguage":"swift"},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct/init(rawValue:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct\/init(rawvalue:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/init(rawValue:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_RESISTANCE":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MODE_RESISTANCE"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"MODE_RESISTANCE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"title":"MODE_RESISTANCE","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_RESISTANCE","role":"symbol","url":"\/documentation\/neirykit\/mode_resistance"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STOPPPG":{"role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MODE_STOPPPG"}],"type":"topic","title":"MODE_STOPPPG","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_STOPPPG"},{"kind":"text","text":": "},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPPPG","url":"\/documentation\/neirykit\/mode_stopppg"},"doc://com.asinenko.NeiryKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s8SendableP"},"doc://com.asinenko.NeiryKit/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s15BitwiseCopyableP"},"doc://com.asinenko.NeiryKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SQ"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_SIGNALANDRESIST":{"url":"\/documentation\/neirykit\/mode_signalandresist","type":"topic","title":"MODE_SIGNALANDRESIST","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNALANDRESIST","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MODE_SIGNALANDRESIST"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceMode","text":"NeiryDeviceMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"MODE_SIGNALANDRESIST"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STARTPPG":{"title":"MODE_STARTPPG","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTPPG","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_STARTPPG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/mode_startppg","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MODE_STARTPPG"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct/rawValue":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/rawValue","abstract":[],"url":"\/documentation\/neirykit\/neirydevicemode-swift.struct\/rawvalue","title":"rawValue","type":"topic"},"doc://com.asinenko.NeiryKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SY"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_POWERDOWN":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_POWERDOWN","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_POWERDOWN"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier","text":"NeiryDeviceMode"}],"title":"MODE_POWERDOWN","url":"\/documentation\/neirykit\/mode_powerdown","abstract":[],"type":"topic","navigatorTitle":[{"text":"MODE_POWERDOWN","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct/Equatable-Implementations":{"url":"\/documentation\/neirykit\/neirydevicemode-swift.struct\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/Equatable-Implementations","type":"topic","kind":"article","title":"Equatable Implementations","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STARTMEMS":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTMEMS","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_STARTMEMS"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","preciseIdentifier":"c:@E@NeiryDeviceMode","kind":"typeIdentifier"}],"abstract":[],"title":"MODE_STARTMEMS","type":"topic","navigatorTitle":[{"text":"MODE_STARTMEMS","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/mode_startmems"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_SIGNAL":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_SIGNAL","kind":"identifier"},{"kind":"text","text":": "},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"role":"symbol","title":"MODE_SIGNAL","url":"\/documentation\/neirykit\/mode_signal","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MODE_SIGNAL"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNAL"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct/init(_:)":{"title":"init(_:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/neirykit\/neirydevicemode-swift.struct\/init(_:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/init(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_STOPMEMS":{"kind":"symbol","url":"\/documentation\/neirykit\/mode_stopmems","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MODE_STOPMEMS","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceMode","text":"NeiryDeviceMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"MODE_STOPMEMS"}],"title":"MODE_STOPMEMS","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPMEMS","type":"topic","abstract":[],"role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/MODE_IDLE":{"url":"\/documentation\/neirykit\/mode_idle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MODE_IDLE"},{"text":": ","kind":"text"},{"text":"NeiryDeviceMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceMode"}],"title":"MODE_IDLE","role":"symbol","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_IDLE","kind":"symbol","navigatorTitle":[{"text":"MODE_IDLE","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","value":"NeiryDeviceMode","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"NeiryDeviceMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_IDLE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_POWERDOWN","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_RESISTANCE","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNAL","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_SIGNALANDRESIST","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTMEMS","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STARTPPG","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPMEMS","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/MODE_STOPPPG"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"NeiryDeviceMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" { ... } "},{"text":"NeiryDeviceMode","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_RESISTANCE\/title","value":"MODE_RESISTANCE"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_RESISTANCE\/fragments","value":[{"text":"MODE_RESISTANCE","kind":"identifier"}],"op":"replace"},{"value":"MODE_STOPPPG","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPPPG\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPPPG\/fragments","value":[{"text":"MODE_STOPPPG","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNALANDRESIST\/title","value":"MODE_SIGNALANDRESIST","op":"replace"},{"value":[{"text":"MODE_SIGNALANDRESIST","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNALANDRESIST\/fragments","op":"replace"},{"value":"MODE_STARTPPG","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTPPG\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTPPG\/fragments","value":[{"text":"MODE_STARTPPG","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_POWERDOWN\/title","value":"MODE_POWERDOWN"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_POWERDOWN\/fragments","value":[{"text":"MODE_POWERDOWN","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTMEMS\/title","value":"MODE_STARTMEMS","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STARTMEMS\/fragments","value":[{"kind":"identifier","text":"MODE_STARTMEMS"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNAL\/title","value":"MODE_SIGNAL","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_SIGNAL\/fragments","value":[{"text":"MODE_SIGNAL","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title","value":"NeiryDeviceMode","op":"replace"},{"value":[{"text":"NeiryDeviceMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPMEMS\/title","value":"MODE_STOPMEMS","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_STOPMEMS\/fragments","value":[{"text":"MODE_STOPMEMS","kind":"identifier"}]},{"op":"replace","value":"MODE_IDLE","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_IDLE\/title"},{"value":[{"kind":"identifier","text":"MODE_IDLE"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1MODE_IDLE\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}