{"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroX","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroY","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroZ","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/timepoint","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/x","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/y","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/z"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/SQ","doc:\/\/com.asinenko.NeiryKit\/SH"],"type":"conformsTo"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NeiryMEMSData"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/neirykit\/neirymemsdata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neirymemsdata"]}],"metadata":{"role":"symbol","modules":[{"name":"NeiryKit"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"NeiryMEMSData","kind":"identifier"}],"title":"NeiryMEMSData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NeiryMEMSData","kind":"identifier"}],"externalID":"c:objc(cs)NeiryMEMSData"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.asinenko.NeiryKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData/timepoint":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/timepoint","url":"\/documentation\/neirykit\/neirymemsdata\/timepoint","navigatorTitle":[{"kind":"identifier","text":"timepoint"}],"title":"timepoint","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timepoint"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData/x":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/x","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"url":"\/documentation\/neirykit\/neirymemsdata\/x","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"x"}],"abstract":[],"title":"x"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject","type":"unresolvable"},"doc://com.asinenko.NeiryKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","type":"unresolvable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData/y":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/y","abstract":[],"url":"\/documentation\/neirykit\/neirymemsdata\/y","navigatorTitle":[{"text":"y","kind":"identifier"}],"kind":"symbol","type":"topic","title":"y","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData/z":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/z","role":"symbol","url":"\/documentation\/neirykit\/neirymemsdata\/z","title":"z","navigatorTitle":[{"kind":"identifier","text":"z"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"z","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData/gyroX":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroX","url":"\/documentation\/neirykit\/neirymemsdata\/gyrox","navigatorTitle":[{"text":"gyroX","kind":"identifier"}],"title":"gyroX","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"gyroX","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData/gyroZ":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gyroZ"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"kind":"symbol","abstract":[],"role":"symbol","title":"gyroZ","navigatorTitle":[{"kind":"identifier","text":"gyroZ"}],"url":"\/documentation\/neirykit\/neirymemsdata\/gyroz","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroZ","type":"topic"},"doc://com.asinenko.NeiryKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SH"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NeiryMEMSData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryMEMSData"}],"url":"\/documentation\/neirykit\/neirymemsdata","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","title":"NeiryMEMSData"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData/gyroY":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroY","url":"\/documentation\/neirykit\/neirymemsdata\/gyroy","navigatorTitle":[{"text":"gyroY","kind":"identifier"}],"title":"gyroY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"gyroY","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[]},"doc://com.asinenko.NeiryKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.asinenko.NeiryKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SQ","type":"unresolvable"},"doc://com.asinenko.NeiryKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"NeiryMEMSData","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"NeiryMEMSData","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NeiryMEMSData"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroX","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroY","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroZ","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/timepoint","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/x","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/y","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/z"],"generated":true,"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"NeiryMEMSData","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"timepoint","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1timepoint\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1timepoint\/fragments","value":[{"text":"timepoint","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1x\/title","op":"replace","value":"x"},{"value":[{"kind":"identifier","text":"x"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1x\/fragments","op":"replace"},{"value":"y","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1y\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1y\/fragments","value":[{"text":"y","kind":"identifier"}]},{"op":"replace","value":"z","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1z\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1z\/fragments","value":[{"text":"z","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"gyroX","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1gyroX\/title"},{"value":[{"kind":"identifier","text":"gyroX"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1gyroX\/fragments","op":"replace"},{"value":"gyroZ","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1gyroZ\/title"},{"value":[{"text":"gyroZ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1gyroZ\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/title","value":"NeiryMEMSData"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/fragments","op":"replace","value":[{"text":"NeiryMEMSData","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"NeiryMEMSData"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/navigatorTitle"},{"value":"gyroY","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1gyroY\/title"},{"value":[{"text":"gyroY","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1gyroY\/fragments"}]}]}