{"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel\/index","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel\/name"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/SQ","doc:\/\/com.asinenko.NeiryKit\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirychannel"]},{"paths":["\/documentation\/neirykit\/neirychannel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NeiryChannel","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"NeiryKit"}],"externalID":"c:objc(cs)NeiryChannel","roleHeading":"Class","navigatorTitle":[{"text":"NeiryChannel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NeiryChannel","kind":"identifier"}],"title":"NeiryChannel"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"sections":[],"references":{"doc://com.asinenko.NeiryKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SQ","title":"Swift.Equatable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryChannel/index":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel\/index","url":"\/documentation\/neirykit\/neirychannel\/index","navigatorTitle":[{"text":"index","kind":"identifier"}],"role":"symbol","title":"index","abstract":[]},"doc://com.asinenko.NeiryKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.asinenko.NeiryKit/SH":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"kind":"symbol","title":"NeiryKit","abstract":[],"role":"collection","url":"\/documentation\/neirykit","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryChannel/name":{"url":"\/documentation\/neirykit\/neirychannel\/name","abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel\/name","title":"name","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"name","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.asinenko.NeiryKit/objc(cs)NSObject":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.asinenko.NeiryKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryChannel":{"url":"\/documentation\/neirykit\/neirychannel","abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel","title":"NeiryChannel","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NeiryChannel"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryChannel"}]},"doc://com.asinenko.NeiryKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"NeiryChannel"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"NeiryChannel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"NeiryChannel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel\/index","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryChannel\/name"],"anchor":"Instance-Properties"}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryChannel"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"index","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel~1index\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel~1index\/fragments","value":[{"text":"index","kind":"identifier"}],"op":"replace"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel~1name\/title"},{"op":"replace","value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel~1name\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/title","op":"replace","value":"NeiryChannel"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/fragments","value":[{"text":"NeiryChannel","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NeiryChannel"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryChannel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}