{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NeiryPPGData","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"NeiryKit"}],"symbolKind":"class","role":"symbol","title":"NeiryPPGData","navigatorTitle":[{"text":"NeiryPPGData","kind":"identifier"}],"externalID":"c:objc(cs)NeiryPPGData","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NeiryPPGData","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData\/timepoint","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData\/value"],"generated":true,"title":"Instance Properties"}],"variants":[{"paths":["\/documentation\/neirykit\/neiryppgdata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neiryppgdata"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/SQ","doc:\/\/com.asinenko.NeiryKit\/SH"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData","interfaceLanguage":"swift"},"references":{"doc://com.asinenko.NeiryKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPPGData/timepoint":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData\/timepoint","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timepoint"}],"url":"\/documentation\/neirykit\/neiryppgdata\/timepoint","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timepoint"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"title":"timepoint","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPPGData/value":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"title":"value","url":"\/documentation\/neirykit\/neiryppgdata\/value","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData\/value"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPPGData":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData","abstract":[],"role":"symbol","url":"\/documentation\/neirykit\/neiryppgdata","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryPPGData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryPPGData"}],"type":"topic","title":"NeiryPPGData"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject","type":"unresolvable"},"doc://com.asinenko.NeiryKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","type":"unresolvable"},"doc://com.asinenko.NeiryKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.asinenko.NeiryKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","type":"unresolvable"},"doc://com.asinenko.NeiryKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SH","type":"unresolvable"},"doc://com.asinenko.NeiryKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"NeiryPPGData"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NeiryPPGData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"NeiryPPGData","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData\/timepoint","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData\/value"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"op":"replace"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryPPGData"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"timepoint","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData~1timepoint\/title"},{"op":"replace","value":[{"text":"timepoint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData~1timepoint\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData~1value\/title","value":"value"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData~1value\/fragments","value":[{"kind":"identifier","text":"value"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/title","value":"NeiryPPGData","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryPPGData"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/fragments"},{"value":[{"kind":"identifier","text":"NeiryPPGData"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}