{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject"],"kind":"relationships"},{"kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry"],"title":"Conforming Types"}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onBattery(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onConnected(_:channels:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onDevices(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onDisconnected()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onEEGData(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onError(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onErrorMessage(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onLog(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onMEMSData(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onPPGData(_:)"],"generated":true,"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate"]},{"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"protocol","title":"NeiryClientObjcDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"modules":[{"name":"NeiryKit"}],"externalID":"c:objc(pl)NeiryClientObjcDelegate","roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onError(_:)":{"title":"onError(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onError(_:)","url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onerror(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onError:","kind":"identifier"}],"abstract":[],"role":"symbol","required":true},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onConnected(_:channels:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConnected","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryDevice","kind":"typeIdentifier","text":"NeiryDevice"},{"text":", ","kind":"text"},{"text":"channels","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NeiryChannel","preciseIdentifier":"c:objc(cs)NeiryChannel","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onconnected(_:channels:)","required":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onConnected(_:channels:)","navigatorTitle":[{"kind":"identifier","text":"onConnected:channels:"}],"title":"onConnected(_:channels:)","role":"symbol","type":"topic","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onLog(_:)":{"role":"symbol","url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onlog(_:)","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onLog(_:)","abstract":[],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onLog","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onLog:","kind":"identifier"}],"title":"onLog(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onEEGData(_:)":{"required":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onEEGData(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onEEGData","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:objc(cs)NeiryEEGData","text":"NeiryEEGData","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/oneegdata(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onEEGData:"}],"abstract":[],"title":"onEEGData(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onMEMSData(_:)":{"type":"topic","required":true,"title":"onMEMSData(_:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onMEMSData(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMEMSData","kind":"identifier"},{"kind":"text","text":"(["},{"text":"NeiryMEMSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryMEMSData"},{"kind":"text","text":"])"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"onMEMSData:","kind":"identifier"}],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onmemsdata(_:)"},"doc://com.asinenko.NeiryKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onDevices(_:)":{"title":"onDevices(_:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onDevices(_:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/ondevices(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onDevices","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryDevice","kind":"typeIdentifier","text":"NeiryDevice"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"onDevices:","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onErrorMessage(_:)":{"type":"topic","required":true,"title":"onErrorMessage(_:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onErrorMessage(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onErrorMessage","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onErrorMessage:"}],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onerrormessage(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onBattery(_:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onbattery(_:)","title":"onBattery(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onBattery","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onBattery:"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onBattery(_:)","required":true},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onPPGData(_:)":{"required":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onPPGData(_:)","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onppgdata(_:)","navigatorTitle":[{"text":"onPPGData:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPPGData"},{"text":"([","kind":"text"},{"text":"NeiryPPGData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryPPGData"},{"text":"])","kind":"text"}],"kind":"symbol","role":"symbol","title":"onPPGData(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","title":"NeiryClientObjcDelegate","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"type":"topic","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onDisconnected()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDisconnected"}],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/ondisconnected()","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onDisconnected","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onDisconnected()","title":"onDisconnected()","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"NeiryClientObjcDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"NeiryClientObjcDelegate","kind":"identifier"}]},{"value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onBattery(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onConnected(_:channels:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onDevices(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onDisconnected()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onEEGData(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onError(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onErrorMessage(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onLog(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onMEMSData(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onPPGData(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject"],"kind":"relationships"},{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onError(_:)\/title","value":"onError:"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onError(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onError:","kind":"identifier"}]},{"op":"replace","value":"onConnected:channels:","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onConnected(_:channels:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConnected:channels:"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onConnected(_:channels:)\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title","value":"Neiry","op":"replace"},{"value":[{"text":"Neiry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle","value":[{"text":"Neiry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onLog(_:)\/title","op":"replace","value":"onLog:"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onLog(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onLog:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onEEGData(_:)\/title","value":"onEEGData:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onEEGData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onEEGData:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onMEMSData(_:)\/title","op":"replace","value":"onMEMSData:"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onMEMSData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMEMSData:","kind":"identifier"}],"op":"replace"},{"value":"onDevices:","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onDevices(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onDevices(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDevices:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onErrorMessage(_:)\/title","value":"onErrorMessage:"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onErrorMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onErrorMessage:"}],"op":"replace"},{"value":"onBattery:","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onBattery(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onBattery(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onBattery:"}],"op":"replace"},{"value":"onPPGData:","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onPPGData(_:)\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onPPGData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onPPGData:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/title","value":"NeiryClientObjcDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/fragments","op":"replace","value":[{"text":"NeiryClientObjcDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/navigatorTitle"},{"value":"onDisconnected","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onDisconnected()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onDisconnected()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onDisconnected","kind":"identifier"}]}]}]}