{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Neiry"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Neiry","kind":"identifier"}],"modules":[{"name":"NeiryKit"}],"externalID":"c:@M@NeiryKit@objc(cs)Neiry","symbolKind":"class","roleHeading":"Class","title":"Neiry"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/init()"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/delegate"]},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/connect(to:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/create(address:name:type:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/disconnect()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/getBatteyLevel()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/requestDevices()"],"title":"Instance Methods"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/getClientVersion()"],"anchor":"Type-Methods"},{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/NeiryClientObjcDelegate-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","doc:\/\/com.asinenko.NeiryKit\/s8CopyableP","doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/SQ","doc:\/\/com.asinenko.NeiryKit\/SH"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiry"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neiry"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/NeiryClientObjcDelegate-Implementations":{"kind":"article","url":"\/documentation\/neirykit\/neiry\/neiryclientobjcdelegate-implementations","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/NeiryClientObjcDelegate-Implementations","abstract":[],"type":"topic","title":"NeiryClientObjcDelegate Implementations","role":"collectionGroup"},"doc://com.asinenko.NeiryKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/connect(to:)":{"title":"connect(to:)","url":"\/documentation\/neirykit\/neiry\/connect(to:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/connect(to:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NeiryDevice","preciseIdentifier":"c:objc(cs)NeiryDevice"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Метод вызывается для подключения к устройству"}]},"doc://com.asinenko.NeiryKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SH","title":"Swift.Hashable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.asinenko.NeiryKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/getBatteyLevel()":{"title":"getBatteyLevel()","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/getBatteyLevel()","abstract":[{"type":"text","text":"Метод для получения уровня батареи"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiry\/getbatteylevel()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getBatteyLevel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/requestDevices()":{"abstract":[{"type":"text","text":"Запрашиваем список устройств"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/requestDevices()","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiry\/requestdevices()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestDevices","kind":"identifier"},{"text":"()","kind":"text"}],"title":"requestDevices()","role":"symbol"},"doc://com.asinenko.NeiryKit/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s8CopyableP","title":"Swift.Copyable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/create(address:name:type:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/create(address:name:type:)","abstract":[{"type":"text","text":"Функция создает и инициализирует CapsuleClient"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8NeiryKit14CapsuleAddressO","text":"CapsuleAddress"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/neirykit\/neiry\/create(address:name:type:)","type":"topic","kind":"symbol","title":"create(address:name:type:)","role":"symbol"},"doc://com.asinenko.NeiryKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/SQ","title":"Swift.Equatable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/getClientVersion()":{"kind":"symbol","role":"symbol","abstract":[{"text":"Метод для получения версии клиента CapsuleClient","type":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/getClientVersion()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getClientVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/neirykit\/neiry\/getclientversion()","title":"getClientVersion()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/init()":{"abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/neirykit\/neiry\/init()","kind":"symbol","title":"init()","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/init()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","title":"NeiryClientObjcDelegate","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"type":"topic","kind":"symbol"},"doc://com.asinenko.NeiryKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/disconnect()":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Функция выключает CapsuleClient"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/disconnect()","title":"disconnect()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnect"},{"text":"()","kind":"text"}],"url":"\/documentation\/neirykit\/neiry\/disconnect()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/delegate":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/delegate","title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"NeiryDelegate","preciseIdentifier":"s:8NeiryKit0A8DelegateP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/neirykit\/neiry\/delegate"},"doc://com.asinenko.NeiryKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"Neiry"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"Neiry","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Neiry"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/init()"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/NeiryClientObjcDelegate-Implementations"],"anchor":"Default-Implementations"}]},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Neiry","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"value":"Neiry","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title"},{"value":[{"text":"Neiry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle","value":[{"kind":"identifier","text":"Neiry"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1init()\/title","value":"init","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1init()\/fragments","op":"replace"},{"value":"NeiryClientObjcDelegate","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/navigatorTitle"}]}]}