{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NeiryClientObjc","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/neirykit\/neiryclientobjc"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neiryclientobjc"]}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/delegate"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/connect(to:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/createClient(withName:address:deviceType:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/disconnect()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getBatteryLevel()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getErrorByNumber(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/requestDevices()"]},{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getClientVersion()"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","doc:\/\/com.asinenko.NeiryKit\/SQ","doc:\/\/com.asinenko.NeiryKit\/SH"]}],"metadata":{"roleHeading":"Class","title":"NeiryClientObjc","modules":[{"name":"NeiryKit"}],"navigatorTitle":[{"text":"NeiryClientObjc","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)NeiryClientObjc","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryClientObjc"}],"symbolKind":"class"},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.asinenko.NeiryKit/objc(cs)NSObject":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/requestDevices()":{"title":"requestDevices()","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestDevices"}],"role":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiryclientobjc\/requestdevices()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestDevices","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/requestDevices()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/getClientVersion()":{"title":"getClientVersion()","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getClientVersion()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getClientVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","url":"\/documentation\/neirykit\/neiryclientobjc\/getclientversion()","abstract":[],"type":"topic","navigatorTitle":[{"text":"getClientVersion","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.asinenko.NeiryKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/createClient(withName:address:deviceType:)":{"role":"symbol","kind":"symbol","title":"createClient(withName:address:deviceType:)","navigatorTitle":[{"text":"createClientWithName:address:deviceType:","kind":"identifier"}],"url":"\/documentation\/neirykit\/neiryclientobjc\/createclient(withname:address:devicetype:)","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/createClient(withName:address:deviceType:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createClient"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType"},{"text":")","kind":"text"}]},"doc://com.asinenko.NeiryKit/s7CVarArgP":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.asinenko.NeiryKit/SQ":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.asinenko.NeiryKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/delegate":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"text":"NeiryClientObjcDelegate","preciseIdentifier":"c:objc(pl)NeiryClientObjcDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"delegate","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/delegate","role":"symbol","url":"\/documentation\/neirykit\/neiryclientobjc\/delegate"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc":{"type":"topic","title":"NeiryClientObjc","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryClientObjc","kind":"identifier"}],"navigatorTitle":[{"text":"NeiryClientObjc","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc","url":"\/documentation\/neirykit\/neiryclientobjc"},"doc://com.asinenko.NeiryKit/SH":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/getBatteryLevel()":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBatteryLevel"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"getBatteryLevel"}],"url":"\/documentation\/neirykit\/neiryclientobjc\/getbatterylevel()","kind":"symbol","title":"getBatteryLevel()","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getBatteryLevel()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/getErrorByNumber(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getErrorByNumber","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","title":"getErrorByNumber(_:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getErrorByNumber(_:)","kind":"symbol","url":"\/documentation\/neirykit\/neiryclientobjc\/geterrorbynumber(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"getErrorByNumber:"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/disconnect()":{"abstract":[],"title":"disconnect()","navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/disconnect()","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiryclientobjc\/disconnect()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/connect(to:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"NeiryDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryDevice"},{"text":")","kind":"text"}],"abstract":[],"title":"connect(to:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"connectTo:"}],"url":"\/documentation\/neirykit\/neiryclientobjc\/connect(to:)","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/connect(to:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"NeiryClientObjc"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"NeiryClientObjc","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"NeiryClientObjc","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/delegate"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/connect(to:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/createClient(withName:address:deviceType:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/disconnect()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getBatteryLevel()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getErrorByNumber(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/requestDevices()"],"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getClientVersion()"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.asinenko.NeiryKit\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryClientObjc"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"requestDevices","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1requestDevices()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"requestDevices","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1requestDevices()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getClientVersion()\/title","value":"getClientVersion"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getClientVersion"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getClientVersion()\/fragments"},{"op":"replace","value":"createClientWithName:address:deviceType:","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1createClient(withName:address:deviceType:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1createClient(withName:address:deviceType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createClientWithName:address:deviceType:","kind":"identifier"}]},{"value":"delegate","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1delegate\/title","op":"replace"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1delegate\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/title","value":"NeiryClientObjc","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryClientObjc"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NeiryClientObjc"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getBatteryLevel()\/title","value":"getBatteryLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getBatteryLevel()\/fragments","value":[{"kind":"text","text":"- "},{"text":"getBatteryLevel","kind":"identifier"}]},{"value":"getErrorByNumber:","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getErrorByNumber(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"getErrorByNumber:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getErrorByNumber(_:)\/fragments"},{"op":"replace","value":"disconnect","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1disconnect()\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1disconnect()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disconnect","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1connect(to:)\/title","value":"connectTo:"},{"value":[{"text":"- ","kind":"text"},{"text":"connectTo:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1connect(to:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}