{"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADBAND"},"metadata":{"externalID":"c:@E@NeiryDeviceType@TYPE_HEADBAND","roleHeading":"Global Variable","symbolKind":"var","modules":[{"name":"NeiryKit"}],"title":"TYPE_HEADBAND","role":"symbol","navigatorTitle":[{"text":"TYPE_HEADBAND","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TYPE_HEADBAND","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType","kind":"typeIdentifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"TYPE_HEADBAND"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/type_headband"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/type_headband"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_HEADBAND":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TYPE_HEADBAND"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType"}],"url":"\/documentation\/neirykit\/type_headband","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_HEADBAND","navigatorTitle":[{"text":"TYPE_HEADBAND","kind":"identifier"}],"title":"TYPE_HEADBAND","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"TYPE_HEADBAND","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"TYPE_HEADBAND","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"TYPE_HEADBAND"}]}]},"op":"replace"},{"op":"replace","value":"TYPE_HEADBAND","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADBAND\/title"},{"value":[{"text":"TYPE_HEADBAND","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_HEADBAND\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title","op":"replace","value":"NeiryDeviceType"},{"value":[{"text":"NeiryDeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"}]}]}