{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/type_any"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/type_any"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TYPE_ANY","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","text":"NeiryDeviceType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"TYPE_ANY","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType"}],"symbolKind":"var","roleHeading":"Global Variable","externalID":"c:@E@NeiryDeviceType@TYPE_ANY","title":"TYPE_ANY","role":"symbol","modules":[{"name":"NeiryKit"}],"navigatorTitle":[{"kind":"identifier","text":"TYPE_ANY"}]},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_ANY","interfaceLanguage":"swift"},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_ANY":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TYPE_ANY"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_ANY","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"}],"title":"TYPE_ANY","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_ANY","role":"symbol","url":"\/documentation\/neirykit\/type_any"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"TYPE_ANY","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TYPE_ANY","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"TYPE_ANY"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_ANY\/title","op":"replace","value":"TYPE_ANY"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_ANY\/fragments","value":[{"text":"TYPE_ANY","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title","op":"replace","value":"NeiryDeviceType"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"}]}]}