{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"TYPE_SINWAVE"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","kind":"typeIdentifier","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/type_sinwave"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/type_sinwave"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType"]]},"metadata":{"title":"TYPE_SINWAVE","role":"symbol","symbolKind":"var","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TYPE_SINWAVE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType","kind":"typeIdentifier"}],"roleHeading":"Global Variable","externalID":"c:@E@NeiryDeviceType@TYPE_SINWAVE","modules":[{"name":"NeiryKit"}],"navigatorTitle":[{"text":"TYPE_SINWAVE","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_SINWAVE","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_SINWAVE":{"title":"TYPE_SINWAVE","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_SINWAVE","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_SINWAVE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"}],"url":"\/documentation\/neirykit\/type_sinwave","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TYPE_SINWAVE"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"TYPE_SINWAVE"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"TYPE_SINWAVE","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"TYPE_SINWAVE","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_SINWAVE\/title","op":"replace","value":"TYPE_SINWAVE"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_SINWAVE\/fragments","value":[{"text":"TYPE_SINWAVE","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title","value":"NeiryDeviceType","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryDeviceType"}],"op":"replace"}]}]}