{"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/type_noise"]},{"paths":["\/documentation\/neirykit\/type_noise"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_NOISE"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TYPE_NOISE"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","text":"NeiryDeviceType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"NeiryKit"}],"symbolKind":"var","title":"TYPE_NOISE","role":"symbol","roleHeading":"Global Variable","navigatorTitle":[{"text":"TYPE_NOISE","kind":"identifier"}],"externalID":"c:@E@NeiryDeviceType@TYPE_NOISE","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"TYPE_NOISE","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType"}]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_NOISE":{"title":"TYPE_NOISE","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_NOISE","url":"\/documentation\/neirykit\/type_noise","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_NOISE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType"}],"navigatorTitle":[{"text":"TYPE_NOISE","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"TYPE_NOISE","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TYPE_NOISE"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"TYPE_NOISE","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title","value":"NeiryDeviceType","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_NOISE\/title","op":"replace","value":"TYPE_NOISE"},{"value":[{"text":"TYPE_NOISE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_NOISE\/fragments","op":"replace"}]}]}