{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TYPE_LSL"},{"kind":"text","text":": "},{"text":"NeiryDeviceType","kind":"typeIdentifier","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_LSL"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType"]]},"sections":[],"metadata":{"symbolKind":"var","roleHeading":"Global Variable","role":"symbol","title":"TYPE_LSL","externalID":"c:@E@NeiryDeviceType@TYPE_LSL","modules":[{"name":"NeiryKit"}],"navigatorTitle":[{"kind":"identifier","text":"TYPE_LSL"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TYPE_LSL","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/neirykit\/type_lsl"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/type_lsl"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_LSL":{"type":"topic","url":"\/documentation\/neirykit\/type_lsl","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_LSL","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TYPE_LSL","kind":"identifier"}],"title":"TYPE_LSL","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"TYPE_LSL","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NeiryDeviceType","text":"NeiryDeviceType","kind":"typeIdentifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"TYPE_LSL","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TYPE_LSL","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"TYPE_LSL","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_LSL\/title","value":"TYPE_LSL","op":"replace"},{"value":[{"kind":"identifier","text":"TYPE_LSL"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_LSL\/fragments"},{"value":"NeiryDeviceType","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments","op":"replace","value":[{"text":"NeiryDeviceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","value":[{"text":"NeiryDeviceType","kind":"identifier"}]}]}]}