{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_IMPULSE"},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"NeiryKit"}],"title":"TYPE_IMPULSE","externalID":"c:@E@NeiryDeviceType@TYPE_IMPULSE","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"TYPE_IMPULSE","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"}],"roleHeading":"Global Variable","symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"TYPE_IMPULSE"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"TYPE_IMPULSE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/type_impulse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/type_impulse"]}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit"],["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/TYPE_IMPULSE":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"TYPE_IMPULSE","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"}],"url":"\/documentation\/neirykit\/type_impulse","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/TYPE_IMPULSE","abstract":[],"title":"TYPE_IMPULSE","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TYPE_IMPULSE","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"TYPE_IMPULSE","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TYPE_IMPULSE"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"TYPE_IMPULSE","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title","value":"NeiryDeviceType"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments","op":"replace","value":[{"text":"NeiryDeviceType","kind":"identifier"}]},{"value":[{"text":"NeiryDeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_IMPULSE\/title","value":"TYPE_IMPULSE","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1TYPE_IMPULSE\/fragments","op":"replace","value":[{"text":"TYPE_IMPULSE","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}