{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"connect","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"device","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","text":"NeiryDevice","preciseIdentifier":"c:objc(cs)NeiryDevice","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/neirykit\/neiry\/connect(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/connect(to:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"NeiryKit"}],"symbolKind":"method","roleHeading":"Instance Method","title":"connect(to:)","externalID":"s:8NeiryKit0A0C7connect2toySo0A6DeviceC_tF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NeiryDevice","kind":"typeIdentifier","text":"NeiryDevice"},{"text":")","kind":"text"}],"role":"symbol"},"abstract":[{"type":"text","text":"Метод вызывается для подключения к устройству"}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/connect(to:)":{"title":"connect(to:)","url":"\/documentation\/neirykit\/neiry\/connect(to:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/connect(to:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NeiryDevice","preciseIdentifier":"c:objc(cs)NeiryDevice"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Метод вызывается для подключения к устройству"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDevice":{"abstract":[],"title":"NeiryDevice","navigatorTitle":[{"text":"NeiryDevice","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDevice"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDevice","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neirydevice"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Neiry","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments","value":[{"kind":"identifier","text":"Neiry"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle","value":[{"kind":"identifier","text":"Neiry"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/title","value":"NeiryDevice"},{"value":[{"kind":"identifier","text":"NeiryDevice"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDevice\/navigatorTitle","op":"replace","value":[{"text":"NeiryDevice","kind":"identifier"}]}]}]}