{"sections":[],"abstract":[{"type":"text","text":"Функция создает и инициализирует CapsuleClient"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"s:8NeiryKit0A0C6create7address4name4typeyAA14CapsuleAddressO_SSSo0A10DeviceTypeVtF","modules":[{"name":"NeiryKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8NeiryKit14CapsuleAddressO","kind":"typeIdentifier","text":"CapsuleAddress"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NeiryDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NeiryDeviceType"},{"text":")","kind":"text"}],"symbolKind":"method","title":"create(address:name:type:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CapsuleAddress","preciseIdentifier":"s:8NeiryKit14CapsuleAddressO","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CapsuleAddress"},{"text":" = .inprocess, ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","kind":"typeIdentifier","text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType"},{"text":" = TYPE_HEADBAND)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"address","content":[{"inlineContent":[{"text":"Адрес inprocess или tcp","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Имя для клиента. можно указать любое","type":"text"}]}],"name":"name"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Тип гарнитуры, к которой будем подключаться","type":"text"}]}],"name":"type"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/create(address:name:type:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiry\/create(address:name:type:)"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/create(address:name:type:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/create(address:name:type:)","abstract":[{"type":"text","text":"Функция создает и инициализирует CapsuleClient"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8NeiryKit14CapsuleAddressO","text":"CapsuleAddress"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"NeiryDeviceType","preciseIdentifier":"c:@E@NeiryDeviceType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/neirykit\/neiry\/create(address:name:type:)","type":"topic","kind":"symbol","title":"create(address:name:type:)","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType":{"title":"NeiryDeviceType","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceType"}],"url":"\/documentation\/neirykit\/neirydevicetype","role":"symbol","kind":"symbol","type":"topic","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/CapsuleAddress":{"title":"CapsuleAddress","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CapsuleAddress"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CapsuleAddress","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/CapsuleAddress","url":"\/documentation\/neirykit\/capsuleaddress","abstract":[],"type":"topic","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]}},"variantOverrides":[{"patch":[{"value":"NeiryDeviceType","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryDeviceType"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType\/navigatorTitle","value":[{"text":"NeiryDeviceType","kind":"identifier"}],"op":"replace"},{"value":"Neiry","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title","op":"replace"},{"value":[{"text":"Neiry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle","value":[{"kind":"identifier","text":"Neiry"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}