{"sections":[],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/getClientVersion()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getClientVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/neirykit\/neiry\/getclientversion()"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Метод для получения версии клиента CapsuleClient"}],"metadata":{"role":"symbol","modules":[{"name":"NeiryKit"}],"roleHeading":"Type Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getClientVersion","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"externalID":"s:8NeiryKit0A0C16getClientVersionSSSgyFZ","title":"getClientVersion()"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/getClientVersion()":{"kind":"symbol","role":"symbol","abstract":[{"text":"Метод для получения версии клиента CapsuleClient","type":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/getClientVersion()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getClientVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/neirykit\/neiry\/getclientversion()","title":"getClientVersion()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title","value":"Neiry"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments","value":[{"text":"Neiry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle","value":[{"text":"Neiry","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}