{"metadata":{"role":"collectionGroup","title":"NeiryClientObjcDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"NeiryKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onBattery(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onConnected(_:channels:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onDevices(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onDisconnected()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onEEGData(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onError(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onErrorMessage(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onLog(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onMEMSData(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onPPGData(_:)"],"title":"Instance Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/NeiryClientObjcDelegate-Implementations"},"variants":[{"paths":["\/documentation\/neirykit\/neiry\/neiryclientobjcdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/neirykit\/neiry\/neiryclientobjcdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onMEMSData(_:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onMEMSData(_:)","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neiry\/onmemsdata(_:)","navigatorTitle":[{"text":"onMEMSData:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMEMSData","kind":"identifier"},{"kind":"text","text":"(["},{"text":"NeiryMEMSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryMEMSData"},{"text":"])","kind":"text"}],"kind":"symbol","role":"symbol","title":"onMEMSData(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onErrorMessage(_:)":{"kind":"symbol","url":"\/documentation\/neirykit\/neiry\/onerrormessage(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onErrorMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onErrorMessage(_:)","navigatorTitle":[{"text":"onErrorMessage:","kind":"identifier"}],"abstract":[],"type":"topic","title":"onErrorMessage(_:)","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onDevices(_:)":{"abstract":[],"title":"onDevices(_:)","navigatorTitle":[{"text":"onDevices:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onDevices"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryDevice","kind":"typeIdentifier","text":"NeiryDevice"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onDevices(_:)","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiry\/ondevices(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onPPGData(_:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onPPGData(_:)","kind":"symbol","type":"topic","title":"onPPGData(_:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPPGData"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:objc(cs)NeiryPPGData","text":"NeiryPPGData","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onPPGData:","kind":"identifier"}],"url":"\/documentation\/neirykit\/neiry\/onppgdata(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onBattery(_:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onBattery(_:)","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neiry\/onbattery(_:)","navigatorTitle":[{"text":"onBattery:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onBattery","kind":"identifier"},{"kind":"text","text":"("},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"onBattery(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onEEGData(_:)":{"abstract":[],"title":"onEEGData(_:)","navigatorTitle":[{"text":"onEEGData:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onEEGData"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryEEGData","kind":"typeIdentifier","text":"NeiryEEGData"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onEEGData(_:)","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiry\/oneegdata(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onDisconnected()":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onDisconnected()","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neiry\/ondisconnected()","navigatorTitle":[{"text":"onDisconnected","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onDisconnected","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","title":"onDisconnected()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onConnected(_:channels:)":{"abstract":[],"title":"onConnected(_:channels:)","navigatorTitle":[{"kind":"identifier","text":"onConnected:channels:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConnected"},{"text":"(","kind":"text"},{"text":"NeiryDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryDevice"},{"text":", ","kind":"text"},{"text":"channels","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NeiryChannel","text":"NeiryChannel","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onConnected(_:channels:)","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiry\/onconnected(_:channels:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onLog(_:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onLog(_:)","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neiry\/onlog(_:)","navigatorTitle":[{"text":"onLog:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onLog"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"onLog(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onError(_:)":{"title":"onError(_:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onError(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"role":"symbol","url":"\/documentation\/neirykit\/neiry\/onerror(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onBattery(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onConnected(_:channels:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onDevices(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onDisconnected()","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onEEGData(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onError(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onErrorMessage(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onLog(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onMEMSData(_:)","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onPPGData(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onMEMSData(_:)\/title","value":"onMEMSData:"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onMEMSData(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMEMSData:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onErrorMessage(_:)\/title","value":"onErrorMessage:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onErrorMessage:"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onErrorMessage(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onDevices(_:)\/title","op":"replace","value":"onDevices:"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onDevices(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onDevices:","kind":"identifier"}]},{"value":"onPPGData:","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onPPGData(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onPPGData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPPGData:"}]},{"value":"onBattery:","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onBattery(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onBattery:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onBattery(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onEEGData(_:)\/title","value":"onEEGData:"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onEEGData(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEEGData:"}]},{"value":"onDisconnected","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onDisconnected()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onDisconnected()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onDisconnected","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onConnected(_:channels:)\/title","value":"onConnected:channels:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onConnected:channels:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onConnected(_:channels:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title","value":"Neiry","op":"replace"},{"value":[{"text":"Neiry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments"},{"value":[{"text":"Neiry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle"},{"op":"replace","value":"onLog:","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onLog(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLog:"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onLog(_:)\/fragments"},{"op":"replace","value":"onError:","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onError(_:)\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onError:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}