{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"NeiryClientObjcDelegate.onEEGData(_:)"},{"text":".","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiry\/oneegdata(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neiry\/oneegdata(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"NeiryKit","navigatorTitle":[{"text":"onEEGData:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onEEGData"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryEEGData","text":"NeiryEEGData"},{"text":"])","kind":"text"}],"modules":[{"name":"NeiryKit"}],"externalID":"c:@CM@NeiryKit@objc(cs)Neiry(im)onEEGData:","symbolKind":"method","roleHeading":"Instance Method","title":"onEEGData(_:)"},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onEEGData(_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onEEGData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"samples"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NeiryEEGData","text":"NeiryEEGData","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/NeiryClientObjcDelegate-Implementations"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryEEGData":{"navigatorTitle":[{"kind":"identifier","text":"NeiryEEGData"}],"role":"symbol","url":"\/documentation\/neirykit\/neiryeegdata","type":"topic","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData","abstract":[],"title":"NeiryEEGData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NeiryEEGData","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onEEGData(_:)":{"abstract":[],"title":"onEEGData(_:)","navigatorTitle":[{"text":"onEEGData:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onEEGData"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryEEGData","kind":"typeIdentifier","text":"NeiryEEGData"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onEEGData(_:)","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiry\/oneegdata(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/NeiryClientObjcDelegate-Implementations":{"kind":"article","url":"\/documentation\/neirykit\/neiry\/neiryclientobjcdelegate-implementations","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/NeiryClientObjcDelegate-Implementations","abstract":[],"type":"topic","title":"NeiryClientObjcDelegate Implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onEEGData:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onEEGData:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"onEEGData:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NeiryEEGData *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"samples"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/title","value":"NeiryEEGData","op":"replace"},{"value":[{"text":"NeiryEEGData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/fragments","op":"replace"},{"value":[{"text":"NeiryEEGData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title","value":"Neiry"},{"op":"replace","value":[{"kind":"identifier","text":"Neiry"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments"},{"op":"replace","value":[{"text":"Neiry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle"},{"value":"onEEGData:","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onEEGData(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onEEGData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onEEGData:","kind":"identifier"}]}]}]}