{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"NeiryClientObjcDelegate.onMEMSData(_:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiry\/onmemsdata(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neiry\/onmemsdata(_:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onMEMSData(_:)"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMEMSData","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"samples","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NeiryMEMSData","preciseIdentifier":"c:objc(cs)NeiryMEMSData","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData"},{"text":"])","kind":"text"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"onMEMSData:","kind":"identifier"}],"title":"onMEMSData(_:)","roleHeading":"Instance Method","role":"symbol","externalID":"c:@CM@NeiryKit@objc(cs)Neiry(im)onMEMSData:","modules":[{"name":"NeiryKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMEMSData","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryMEMSData","text":"NeiryMEMSData"},{"kind":"text","text":"])"}],"extendedModule":"NeiryKit","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/NeiryClientObjcDelegate-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/NeiryClientObjcDelegate-Implementations":{"kind":"article","url":"\/documentation\/neirykit\/neiry\/neiryclientobjcdelegate-implementations","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/NeiryClientObjcDelegate-Implementations","abstract":[],"type":"topic","title":"NeiryClientObjcDelegate Implementations","role":"collectionGroup"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/onMEMSData(_:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/onMEMSData(_:)","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neiry\/onmemsdata(_:)","navigatorTitle":[{"text":"onMEMSData:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMEMSData","kind":"identifier"},{"kind":"text","text":"(["},{"text":"NeiryMEMSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryMEMSData"},{"text":"])","kind":"text"}],"kind":"symbol","role":"symbol","title":"onMEMSData(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NeiryMEMSData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryMEMSData"}],"url":"\/documentation\/neirykit\/neirymemsdata","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","title":"NeiryMEMSData"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"onMEMSData:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMEMSData:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onMEMSData:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NeiryMEMSData *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"samples"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onMEMSData(_:)\/title","value":"onMEMSData:"},{"value":[{"kind":"text","text":"- "},{"text":"onMEMSData:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry~1onMEMSData(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/title","value":"NeiryMEMSData"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/fragments","value":[{"text":"NeiryMEMSData","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryMEMSData"}]},{"value":"Neiry","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments","value":[{"text":"Neiry","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"Neiry"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}