{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestDevices","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiry\/requestdevices()"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/requestDevices()"},"abstract":[{"type":"text","text":"Запрашиваем список устройств"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"NeiryKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestDevices"},{"kind":"text","text":"()"}],"role":"symbol","externalID":"s:8NeiryKit0A0C14requestDevicesyyF","symbolKind":"method","title":"requestDevices()"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry":{"title":"Neiry","role":"symbol","url":"\/documentation\/neirykit\/neiry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Neiry"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Neiry"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/Neiry/requestDevices()":{"abstract":[{"type":"text","text":"Запрашиваем список устройств"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/Neiry\/requestDevices()","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiry\/requestdevices()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestDevices","kind":"identifier"},{"text":"()","kind":"text"}],"title":"requestDevices()","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Neiry","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/fragments","value":[{"kind":"identifier","text":"Neiry"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1Neiry\/navigatorTitle","value":[{"text":"Neiry","kind":"identifier"}]}]}]}