{"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData\/timepoint","interfaceLanguage":"swift"},"metadata":{"title":"timepoint","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timepoint"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"timepoint","kind":"identifier"}],"modules":[{"name":"NeiryKit"}],"externalID":"c:objc(cs)NeiryPPGData(py)timepoint"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiryppgdata\/timepoint"]},{"paths":["\/documentation\/neirykit\/neiryppgdata\/timepoint"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timepoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData"]]},"sections":[],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPPGData/timepoint":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData\/timepoint","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timepoint"}],"url":"\/documentation\/neirykit\/neiryppgdata\/timepoint","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timepoint"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"title":"timepoint","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPPGData":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData","abstract":[],"role":"symbol","url":"\/documentation\/neirykit\/neiryppgdata","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryPPGData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryPPGData"}],"type":"topic","title":"NeiryPPGData"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"timepoint","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"timepoint","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"uint64_t","preciseIdentifier":"c:@T@uint64_t"},{"text":" ","kind":"text"},{"text":"timepoint","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData~1timepoint\/title","value":"timepoint"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData~1timepoint\/fragments","value":[{"kind":"identifier","text":"timepoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/title","value":"NeiryPPGData"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/fragments","value":[{"text":"NeiryPPGData","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"NeiryPPGData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/navigatorTitle"}]}]}