{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicemode-swift.struct\/!=(_:_:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/!=(_:_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/Equatable-Implementations"]]},"metadata":{"title":"!=(_:_:)","modules":[{"name":"NeiryKit","relatedModules":["Swift"]}],"symbolKind":"op","roleHeading":"Operator","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","extendedModule":"Swift","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@NeiryDeviceMode"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct/Equatable-Implementations":{"url":"\/documentation\/neirykit\/neirydevicemode-swift.struct\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/Equatable-Implementations","type":"topic","kind":"article","title":"Equatable Implementations","abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct/!=(_:_:)":{"url":"\/documentation\/neirykit\/neirydevicemode-swift.struct\/!=(_:_:)","type":"topic","title":"!=(_:_:)","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/!=(_:_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title","value":"NeiryDeviceMode","op":"replace"},{"value":[{"text":"NeiryDeviceMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryDeviceMode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}