{"metadata":{"symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"modules":[{"name":"NeiryKit"}],"externalID":"s:So15NeiryDeviceModeVyABSucfc"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/neirykit\/neirydevicemode-swift.struct\/init(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct"]]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/init(_:)","interfaceLanguage":"swift"},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct/init(_:)":{"title":"init(_:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/neirykit\/neirydevicemode-swift.struct\/init(_:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/init(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"NeiryDeviceMode","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments","value":[{"text":"NeiryDeviceMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryDeviceMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}