{"metadata":{"externalID":"s:So15NeiryDeviceModeV8rawValueSuvp","modules":[{"name":"NeiryKit"}],"symbolKind":"property","roleHeading":"Instance Property","title":"rawValue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct"]]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/rawValue","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicemode-swift.struct\/rawvalue"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct":{"type":"topic","url":"\/documentation\/neirykit\/neirydevicemode-swift.struct","abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryDeviceMode"}],"role":"symbol","title":"NeiryDeviceMode","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryDeviceMode","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceMode-swift.struct/rawValue":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceMode-swift.struct\/rawValue","abstract":[],"url":"\/documentation\/neirykit\/neirydevicemode-swift.struct\/rawvalue","title":"rawValue","type":"topic"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/title","op":"replace","value":"NeiryDeviceMode"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/fragments","value":[{"text":"NeiryDeviceMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceMode-swift.struct\/navigatorTitle","value":[{"text":"NeiryDeviceMode","kind":"identifier"}]}]}]}