{"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2"]]},"sections":[],"topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/!=(_:_:)"]}],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"NeiryKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicetype2\/equatable-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2":{"url":"\/documentation\/neirykit\/neirydevicetype2","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType2"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"NeiryDeviceType2"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/!=(_:_:)":{"abstract":[],"title":"!=(_:_:)","type":"topic","role":"symbol","url":"\/documentation\/neirykit\/neirydevicetype2\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/!=(_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"NeiryDeviceType2","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/title"},{"value":[{"text":"NeiryDeviceType2","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/navigatorTitle","op":"replace","value":[{"text":"NeiryDeviceType2","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}