{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headphones"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"NeiryDeviceType2Headphones","kind":"identifier"}],"externalID":"c:@M@NeiryKit@E@NeiryDeviceType2@NeiryDeviceType2Headphones","symbolKind":"case","title":"NeiryDeviceType2.headphones","modules":[{"name":"NeiryKit"}]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/headphones","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headphones","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicetype2\/headphones"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neirydevicetype2\/headphones"]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/headphones":{"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"headphones","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/headphones","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2Headphones","kind":"identifier"}],"title":"NeiryDeviceType2.headphones","kind":"symbol","url":"\/documentation\/neirykit\/neirydevicetype2\/headphones"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2":{"url":"\/documentation\/neirykit\/neirydevicetype2","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType2"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"NeiryDeviceType2"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"NeiryDeviceType2Headphones","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"NeiryDeviceType2Headphones","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"NeiryDeviceType2Headphones","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1headphones\/title","value":"NeiryDeviceType2Headphones","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1headphones\/fragments","op":"replace","value":[{"text":"NeiryDeviceType2Headphones","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/title","value":"NeiryDeviceType2"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/fragments","op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceType2"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/navigatorTitle","value":[{"text":"NeiryDeviceType2","kind":"identifier"}]}]}]}