{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicetype2\/noise"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neirydevicetype2\/noise"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"noise","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/noise","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2"]]},"metadata":{"modules":[{"name":"NeiryKit"}],"symbolKind":"case","roleHeading":"Case","title":"NeiryDeviceType2.noise","navigatorTitle":[{"text":"NeiryDeviceType2Noise","kind":"identifier"}],"externalID":"c:@M@NeiryKit@E@NeiryDeviceType2@NeiryDeviceType2Noise","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"noise","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/noise":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/noise","title":"NeiryDeviceType2.noise","url":"\/documentation\/neirykit\/neirydevicetype2\/noise","abstract":[],"navigatorTitle":[{"text":"NeiryDeviceType2Noise","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noise"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2":{"url":"\/documentation\/neirykit\/neirydevicetype2","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType2"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"NeiryDeviceType2"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"NeiryDeviceType2Noise","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"NeiryDeviceType2Noise"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"NeiryDeviceType2Noise"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1noise\/title","value":"NeiryDeviceType2Noise","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1noise\/fragments","value":[{"text":"NeiryDeviceType2Noise","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/title","value":"NeiryDeviceType2"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/fragments","value":[{"text":"NeiryDeviceType2","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceType2"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/navigatorTitle"}]}]}