{"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2"]]},"metadata":{"modules":[{"name":"NeiryKit"}],"role":"collectionGroup","roleHeading":"API Collection","title":"RawRepresentable Implementations"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/neirykit\/neirydevicetype2\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/hashValue"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/hash(into:)"]}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/hash(into:)":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/hash(into:)","title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"url":"\/documentation\/neirykit\/neirydevicetype2\/hash(into:)","abstract":[],"kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2":{"url":"\/documentation\/neirykit\/neirydevicetype2","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType2"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"NeiryDeviceType2"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/hashValue":{"url":"\/documentation\/neirykit\/neirydevicetype2\/hashvalue","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"type":"topic","role":"symbol","title":"hashValue","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/hashValue"}},"variantOverrides":[{"patch":[{"value":"NeiryDeviceType2","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryDeviceType2"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/navigatorTitle","value":[{"text":"NeiryDeviceType2","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}