{"metadata":{"externalID":"c:@M@NeiryKit@E@NeiryDeviceType2@NeiryDeviceType2Undefined","role":"symbol","roleHeading":"Case","modules":[{"name":"NeiryKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"navigatorTitle":[{"text":"NeiryDeviceType2Undefined","kind":"identifier"}],"symbolKind":"case","title":"NeiryDeviceType2.undefined"},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/undefined","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirydevicetype2\/undefined"]},{"paths":["\/documentation\/neirykit\/neirydevicetype2\/undefined"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2":{"url":"\/documentation\/neirykit\/neirydevicetype2","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryDeviceType2"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2","type":"topic","navigatorTitle":[{"text":"NeiryDeviceType2","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"NeiryDeviceType2"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryDeviceType2/undefined":{"title":"NeiryDeviceType2.undefined","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryDeviceType2\/undefined","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/neirykit\/neirydevicetype2\/undefined","type":"topic","abstract":[],"navigatorTitle":[{"text":"NeiryDeviceType2Undefined","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"NeiryDeviceType2Undefined","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"NeiryDeviceType2Undefined","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"NeiryDeviceType2Undefined","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"NeiryDeviceType2","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/fragments","op":"replace","value":[{"text":"NeiryDeviceType2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NeiryDeviceType2"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1undefined\/title","value":"NeiryDeviceType2Undefined"},{"value":[{"text":"NeiryDeviceType2Undefined","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryDeviceType2~1undefined\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}