{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate"]]},"sections":[],"metadata":{"title":"onBattery(_:)","required":true,"externalID":"c:objc(pl)NeiryClientObjcDelegate(im)onBattery:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onBattery:"}],"role":"symbol","modules":[{"name":"NeiryKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onBattery"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBattery","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"level","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/onbattery(_:)"]},{"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/onbattery(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onBattery(_:)","interfaceLanguage":"swift"},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","title":"NeiryClientObjcDelegate","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"type":"topic","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onBattery(_:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onbattery(_:)","title":"onBattery(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onBattery","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onBattery:"}],"abstract":[],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onBattery(_:)","required":true}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"onBattery:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onBattery:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onBattery:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"level"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/title","op":"replace","value":"NeiryClientObjcDelegate"},{"value":[{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onBattery(_:)\/title","value":"onBattery:"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onBattery(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBattery:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}