{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onEEGData"},{"text":"([","kind":"text"},{"text":"NeiryEEGData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryEEGData"},{"kind":"text","text":"])"}],"roleHeading":"Instance Method","required":true,"symbolKind":"method","externalID":"c:objc(pl)NeiryClientObjcDelegate(im)onEEGData:","title":"onEEGData(_:)","role":"symbol","modules":[{"name":"NeiryKit"}],"navigatorTitle":[{"kind":"identifier","text":"onEEGData:"}]},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate"]]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onEEGData(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/oneegdata(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/oneegdata(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onEEGData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"samples","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NeiryEEGData","text":"NeiryEEGData","kind":"typeIdentifier","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onEEGData(_:)":{"required":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onEEGData(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onEEGData","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:objc(cs)NeiryEEGData","text":"NeiryEEGData","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/oneegdata(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onEEGData:"}],"abstract":[],"title":"onEEGData(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryEEGData":{"navigatorTitle":[{"kind":"identifier","text":"NeiryEEGData"}],"role":"symbol","url":"\/documentation\/neirykit\/neiryeegdata","type":"topic","kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryEEGData","abstract":[],"title":"NeiryEEGData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NeiryEEGData","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","title":"NeiryClientObjcDelegate","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onEEGData:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onEEGData:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onEEGData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NeiryEEGData *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"samples"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onEEGData(_:)\/title","op":"replace","value":"onEEGData:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onEEGData:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onEEGData(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/title","op":"replace","value":"NeiryEEGData"},{"op":"replace","value":[{"text":"NeiryEEGData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryEEGData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NeiryEEGData"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/title","value":"NeiryClientObjcDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}]}]}]}