{"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/onerror(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/onerror(_:)"]}],"metadata":{"required":true,"role":"symbol","externalID":"c:objc(pl)NeiryClientObjcDelegate(im)onError:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"modules":[{"name":"NeiryKit"}],"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"symbolKind":"method","roleHeading":"Instance Method","title":"onError(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onError(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onError(_:)":{"title":"onError(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onError(_:)","url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onerror(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onError:","kind":"identifier"}],"abstract":[],"role":"symbol","required":true},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","title":"NeiryClientObjcDelegate","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onError:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onError:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onError:"},{"text":"(","kind":"text"},{"text":"int","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onError(_:)\/title","value":"onError:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onError(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onError:"}]},{"value":"NeiryClientObjcDelegate","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/fragments","value":[{"text":"NeiryClientObjcDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}