{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate"]]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onMEMSData(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/onmemsdata(_:)"]},{"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/onmemsdata(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(pl)NeiryClientObjcDelegate(im)onMEMSData:","title":"onMEMSData(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMEMSData"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:objc(cs)NeiryMEMSData","kind":"typeIdentifier","text":"NeiryMEMSData"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMEMSData:"}],"modules":[{"name":"NeiryKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMEMSData"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"samples","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryMEMSData","text":"NeiryMEMSData","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData"},{"text":"])","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NeiryMEMSData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryMEMSData"}],"url":"\/documentation\/neirykit\/neirymemsdata","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","title":"NeiryMEMSData"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onMEMSData(_:)":{"type":"topic","required":true,"title":"onMEMSData(_:)","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onMEMSData(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMEMSData","kind":"identifier"},{"kind":"text","text":"(["},{"text":"NeiryMEMSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryMEMSData"},{"kind":"text","text":"])"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"onMEMSData:","kind":"identifier"}],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onmemsdata(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","title":"NeiryClientObjcDelegate","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"type":"topic","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onMEMSData:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMEMSData:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onMEMSData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NeiryMEMSData *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"samples","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"NeiryMEMSData","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/fragments","value":[{"text":"NeiryMEMSData","kind":"identifier"}],"op":"replace"},{"value":[{"text":"NeiryMEMSData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onMEMSData(_:)\/title","value":"onMEMSData:"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onMEMSData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMEMSData:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/title","value":"NeiryClientObjcDelegate"},{"value":[{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}]}]}]}