{"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onPPGData(_:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onPPGData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"samples","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NeiryPPGData","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData","kind":"typeIdentifier","text":"NeiryPPGData"},{"kind":"text","text":"])"}]}]}],"metadata":{"role":"symbol","modules":[{"name":"NeiryKit"}],"title":"onPPGData(_:)","required":true,"externalID":"c:objc(pl)NeiryClientObjcDelegate(im)onPPGData:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onPPGData:"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPPGData"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"NeiryPPGData","preciseIdentifier":"c:objc(cs)NeiryPPGData"},{"text":"])","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/onppgdata(_:)"]},{"paths":["\/documentation\/neirykit\/neiryclientobjcdelegate\/onppgdata(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryPPGData":{"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryPPGData","abstract":[],"role":"symbol","url":"\/documentation\/neirykit\/neiryppgdata","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NeiryPPGData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryPPGData"}],"type":"topic","title":"NeiryPPGData"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate":{"role":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate","title":"NeiryClientObjcDelegate","abstract":[],"url":"\/documentation\/neirykit\/neiryclientobjcdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NeiryClientObjcDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"type":"topic","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjcDelegate/onPPGData(_:)":{"required":true,"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjcDelegate\/onPPGData(_:)","abstract":[],"type":"topic","url":"\/documentation\/neirykit\/neiryclientobjcdelegate\/onppgdata(_:)","navigatorTitle":[{"text":"onPPGData:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPPGData"},{"text":"([","kind":"text"},{"text":"NeiryPPGData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NeiryPPGData"},{"text":"])","kind":"text"}],"kind":"symbol","role":"symbol","title":"onPPGData(_:)"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onPPGData:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onPPGData:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onPPGData:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NeiryPPGData *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"samples","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"NeiryPPGData","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/title"},{"value":[{"kind":"identifier","text":"NeiryPPGData"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NeiryPPGData"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryPPGData\/navigatorTitle"},{"value":"NeiryClientObjcDelegate","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NeiryClientObjcDelegate"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate\/navigatorTitle","op":"replace","value":[{"text":"NeiryClientObjcDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onPPGData(_:)\/title","op":"replace","value":"onPPGData:"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjcDelegate~1onPPGData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onPPGData:","kind":"identifier"}],"op":"replace"}]}]}