{"variants":[{"paths":["\/documentation\/neirykit\/neiryclientobjc\/disconnect()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neiryclientobjc\/disconnect()"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/disconnect()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnect"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:objc(cs)NeiryClientObjc(im)disconnect","roleHeading":"Instance Method","title":"disconnect()","symbolKind":"method","modules":[{"name":"NeiryKit"}]},"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc":{"type":"topic","title":"NeiryClientObjc","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryClientObjc","kind":"identifier"}],"navigatorTitle":[{"text":"NeiryClientObjc","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc","url":"\/documentation\/neirykit\/neiryclientobjc"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/disconnect()":{"abstract":[],"title":"disconnect()","navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/disconnect()","kind":"symbol","type":"topic","url":"\/documentation\/neirykit\/neiryclientobjc\/disconnect()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"disconnect","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"disconnect","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/title","value":"NeiryClientObjc","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/fragments","value":[{"text":"NeiryClientObjc","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/navigatorTitle","value":[{"text":"NeiryClientObjc","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1disconnect()\/title","value":"disconnect"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1disconnect()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnect"}]}]}]}