{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc"]]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getBatteryLevel()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/neirykit\/neiryclientobjc\/getbatterylevel()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/neirykit\/neiryclientobjc\/getbatterylevel()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"NeiryKit"}],"role":"symbol","externalID":"c:objc(cs)NeiryClientObjc(im)getBatteryLevel","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getBatteryLevel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"getBatteryLevel","kind":"identifier"}],"roleHeading":"Instance Method","title":"getBatteryLevel()","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBatteryLevel"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/getBatteryLevel()":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBatteryLevel"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"getBatteryLevel"}],"url":"\/documentation\/neirykit\/neiryclientobjc\/getbatterylevel()","kind":"symbol","title":"getBatteryLevel()","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getBatteryLevel()"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc":{"type":"topic","title":"NeiryClientObjc","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryClientObjc","kind":"identifier"}],"navigatorTitle":[{"text":"NeiryClientObjc","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc","url":"\/documentation\/neirykit\/neiryclientobjc"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getBatteryLevel"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getBatteryLevel"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getBatteryLevel"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getBatteryLevel()\/title","value":"getBatteryLevel"},{"value":[{"kind":"text","text":"- "},{"text":"getBatteryLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getBatteryLevel()\/fragments"},{"op":"replace","value":"NeiryClientObjc","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/fragments","value":[{"kind":"identifier","text":"NeiryClientObjc"}]},{"value":[{"kind":"identifier","text":"NeiryClientObjc"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}