{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getClientVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc"]]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getClientVersion()","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","externalID":"c:objc(cs)NeiryClientObjc(cm)getClientVersion","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getClientVersion"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"NeiryKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getClientVersion"}],"title":"getClientVersion()"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neiryclientobjc\/getclientversion()"]},{"paths":["\/documentation\/neirykit\/neiryclientobjc\/getclientversion()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc/getClientVersion()":{"title":"getClientVersion()","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc\/getClientVersion()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getClientVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","url":"\/documentation\/neirykit\/neiryclientobjc\/getclientversion()","abstract":[],"type":"topic","navigatorTitle":[{"text":"getClientVersion","kind":"identifier"}]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryClientObjc":{"type":"topic","title":"NeiryClientObjc","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NeiryClientObjc","kind":"identifier"}],"navigatorTitle":[{"text":"NeiryClientObjc","kind":"identifier"}],"identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryClientObjc","url":"\/documentation\/neirykit\/neiryclientobjc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getClientVersion"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getClientVersion"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"getClientVersion","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"getClientVersion","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getClientVersion()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getClientVersion"}],"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc~1getClientVersion()\/fragments","op":"replace"},{"value":"NeiryClientObjc","op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/title"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/fragments","value":[{"text":"NeiryClientObjc","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryClientObjc\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NeiryClientObjc"}]}]}]}