{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"gyroX","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"title":"gyroX","navigatorTitle":[{"kind":"identifier","text":"gyroX"}],"modules":[{"name":"NeiryKit"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"c:objc(cs)NeiryMEMSData(py)gyroX","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gyroX"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroX","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/neirykit\/neirymemsdata\/gyrox"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/neirykit\/neirymemsdata\/gyrox"]}],"hierarchy":{"paths":[["doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData"]]},"references":{"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData/gyroX":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData\/gyroX","url":"\/documentation\/neirykit\/neirymemsdata\/gyrox","navigatorTitle":[{"text":"gyroX","kind":"identifier"}],"title":"gyroX","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"gyroX","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"abstract":[]},"doc://com.asinenko.NeiryKit/documentation/NeiryKit":{"title":"NeiryKit","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit","url":"\/documentation\/neirykit","kind":"symbol"},"doc://com.asinenko.NeiryKit/documentation/NeiryKit/NeiryMEMSData":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NeiryMEMSData"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NeiryMEMSData"}],"url":"\/documentation\/neirykit\/neirymemsdata","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.asinenko.NeiryKit\/documentation\/NeiryKit\/NeiryMEMSData","title":"NeiryMEMSData"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"gyroX"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"gyroX"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gyroX"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1gyroX\/title","value":"gyroX","op":"replace"},{"value":[{"text":"gyroX","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData~1gyroX\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/title","value":"NeiryMEMSData"},{"op":"replace","path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/fragments","value":[{"kind":"identifier","text":"NeiryMEMSData"}]},{"path":"\/references\/doc:~1~1com.asinenko.NeiryKit~1documentation~1NeiryKit~1NeiryMEMSData\/navigatorTitle","op":"replace","value":[{"text":"NeiryMEMSData","kind":"identifier"}]}]}]}